### PR TITLE
convert book abbreviation in \id marker to uppercase

### PR DESCRIPTION
**Pull request by mshannon-sil**
When retrieving the book abbreviation from the \id marker in a usfm file, convert it to uppercase, so that extracting the corpora will not result in blank output when the book id in the usfm file is lowercase.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/60)

### CODE REVIEW

**Comment by johnml1135** [comment]
Have you checked that you caught all occurrences of this?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/60)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
It would be good to add a unit test to cover this case.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/60#-:-NitdKue8t0OKbZP1ZNn:bhx7ogm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Comment by mshannon-sil** [comment]
@johnml1135 Yes there's two places where `_get_id()` is defined, one in `usfm_file_text.py` and the other in `usfm_zip_text.py`. When I changed these, the extract_corpora script worked correctly in SILNLP.

@ddaspit Sounds good, I'll take a look at adding a unit test.

**Comment by mshannon-sil** [comment]
@ddaspit I added the unit test.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/60#-:-Nj8aL5QCrEbZ3g4a8mD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
