### PR TITLE
Better error messages for #62

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/63)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/63)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/machine.py/63#-NjhtAYb4XqtUHXXWjCw:-NjhtAYb4XqtUHXXWjCx:bx2wspt) ([raw file](https://github.com/sillsdev/machine.py/blob/7f7d8e9186d77b9e3220ced9b1f4b5f319999f48/machine/translation/huggingface/hugging_face_nmt_engine.py#L52)):*
> ```Python
>                 raise ValueError(
>                     f"'{src_lang}' is not a valid language code. This error can happen when "
>                     + "there is no matching training data and the language code is not in the NLLB-200."
> ```

The error message is not appropriate in this context. It references "training data", which is specific to the workflow of a build job. It also references NLLB, but this class is not specific to NLLB. There are two options:
1. Update the message here to give a little more detail, i.e. `The specified model does not support the language code '{src_lang}'.` or something similar.
2. Catch the error in `HuggingFaceNmtModelFactory` and throw a new exception with a more detailed message. In that case, we will need to raise a custom error here, so that we can avoid hiding other `ValueError` instances.

**Comment by mshannon-sil** [comment]
I am in favor of the first option, since saying that "The specified model does not support the language code '{src_lang}'." is clearer terminology and implicitly directs the user to adjust the model to support the language code, rather than saying that a particular language code "is not valid" and having the user potentially think the issue is with the language code itself.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/machine.py/63#-NjhtAYb4XqtUHXXWjCw:-NjmUIhd3UXJundj4i5c:bkt299x) ([raw file](https://github.com/sillsdev/machine.py/blob/7f7d8e9186d77b9e3220ced9b1f4b5f319999f48/machine/translation/huggingface/hugging_face_nmt_engine.py#L52)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The error message is not appropriate in this context. It references "training data", which is specific to the workflow of a build job. It also references NLLB, but this class is not specific to NLLB. There are two options:
1. Update the message here to give a little more detail, i.e. `The specified model does not support the language code '{src_lang}'.` or something similar.
2. Catch the error in `HuggingFaceNmtModelFactory` and throw a new exception with a more detailed message. In that case, we will need to raise a custom error here, so that we can avoid hiding other `ValueError` instances.
</blockquote></details>

Option 1 is good enough.  The error is being raised in production because of another issue that is being fixed now.

**Comment by johnml1135** [comment]
Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/63)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 57 at r2](https://reviewable.io/reviews/sillsdev/machine.py/63#-NjmpeQq5LemTaxL52V1:-NjmpeQq5LemTaxL52V2:b-7qkl9l) ([raw file](https://github.com/sillsdev/machine.py/blob/cf606611a8c6bd6bb81936b0ddbbf2ae1f2e2bca/machine/translation/huggingface/hugging_face_nmt_engine.py#L57)):*
> ```Python
>                 and tgt_lang not in additional_special_tokens
>             ):
>                 raise ValueError(f"The specified model does not support the language code '{src_lang}'")
> ```

This should be `{tgt_lang}`.

**Review by johnml1135 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/63)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 57 at r2](https://reviewable.io/reviews/sillsdev/machine.py/63#-NjmpeQq5LemTaxL52V1:-NjnI17p1dkYFRhaCjXa:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/cf606611a8c6bd6bb81936b0ddbbf2ae1f2e2bca/machine/translation/huggingface/hugging_face_nmt_engine.py#L57)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `{tgt_lang}`.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/63#-:-NjnuhtzA2BnAciP615w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
