### PR TITLE
Docker 2

### PR DESCRIPTION
**Pull request by johnml1135**
To make running a job in NLLB work:
* Fix docker build (add all dependencies)
* Poetry - some "development" dependencies are needed in general - move them
* Resolve model saving bug - #14

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/15)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/15)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`poetry.toml` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpZQ3kDss98EkbucuQ:-NWpZQ3kDss98EkbucuR:b-r0otwr) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/poetry.toml#L2)):*
> ```TOML
> [virtualenvs]
> in-project = true
> ```

I would rather leave it up to each developer to decide where virtualenvs are located.
___
*[`pyproject.toml` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpZn-r2Rh2JiTZXiCA:-NWpZn-r2Rh2JiTZXiCB:b-4bnptl) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L71)):*
> ```TOML
> transformers = "^4.29.1"
> sacremoses = "^0.0.53"
> torch = {version = "2.0.0", markers = "sys_platform == 'win32' or sys_platform == 'linux'"}
> ```

I intentionally did not include PyTorch as a dependency. There are many different versions of PyTorch to support different CUDA versions or CPU. I wanted to give flexibility to the consumer of Machine to choose which is appropriate for their application. This is also true of Tensorflow.
___
*[`pyproject.toml` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_jN16OwTVkP9_gDx:-NWp_jN16OwTVkP9_gDy:bmwjhub) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L74)):*
> ```TOML
> accelerate = {version = "^0.19.0", markers = "sys_platform == 'win32' or sys_platform == 'linux'"}
> tensorflow = "^2.8.0"
> pandas = "^1.3.0"
> ```

I did not want to require that Pandas was installed.
___
*[`pyproject.toml` line 75 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_qBSDgSTB9sRll6X:-NWp_qBSDgSTB9sRll6Y:b-57fnw3) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L75)):*
> ```TOML
> tensorflow = "^2.8.0"
> pandas = "^1.3.0"
> datasets = "^2.4.0"
> ```

I did not want to require that HF datasets was installed.
___
*[`pyproject.toml` line 87 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_yKyCIHEyDOxL0Sp:-NWp_yKyCIHEyDOxL0Sq:b-kdjnps) ([raw file](https://github.com/sillsdev/machine.py/blob/17c016f9025bd3e922f26175696160a1ba1a7a2d/pyproject.toml#L87)):*
> ```TOML
> 
> [tool.poetry.extras]
> sentencepiece = ["sentencepiece"]
> ```

Why did you remove the sentencepiece extra?
___
*[`samples/clearml_run_test.py` line 1 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpa6vl-IoH0PMR_qE_:-NWpa6vl-IoH0PMR_qEa:b-tsgj7) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/samples/clearml_run_test.py#L1)):*
> ```Python
> from machine.jobs.build_nmt_engine import run
> ```

What is the purpose of this script? If it is for development/debugging purposes, you can just use the "build_nmt_engine" configuration defined in the launch.json.

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 75 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_qBSDgSTB9sRll6X:-NXptnF-0-22_ml6yDyW:bwhs3lc) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L75)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I did not want to require that HF datasets was installed.
</blockquote></details>

I disagree - Datasets is used in train in HuggingFaceNmtModelTrainer.  How can we run it without it?

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_jN16OwTVkP9_gDx:-NXptHEQ8LkLMN-B7s8_:bmj1tmg) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L74)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I did not want to require that Pandas was installed.
</blockquote></details>

Moved to dev (I see now how it is only used for TYPE_CHECKING and how the functions are not called).

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 87 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_yKyCIHEyDOxL0Sp:-NXptvql4m0_vxT3mDnT:b6h7gxu) ([raw file](https://github.com/sillsdev/machine.py/blob/17c016f9025bd3e922f26175696160a1ba1a7a2d/pyproject.toml#L87)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why did you remove the sentencepiece extra?
</blockquote></details>

Sentencepiece was moved to a main install.  I moved it to the docker extras.

**Comment by johnml1135** [comment]
*[`samples/clearml_run_test.py` line 1 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpa6vl-IoH0PMR_qE_:-NXq78diCEq6_IRnuJso:b-xymf7h) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/samples/clearml_run_test.py#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is the purpose of this script? If it is for development/debugging purposes, you can just use the "build_nmt_engine" configuration defined in the launch.json.
</blockquote></details>

You are right - i removed the file.

**Review by johnml1135 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/15)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @ddaspit)

___
*[`pyproject.toml` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpZn-r2Rh2JiTZXiCA:-NXplIqX01HiFldXJPZf:b-hg1p6z) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L71)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I intentionally did not include PyTorch as a dependency. There are many different versions of PyTorch to support different CUDA versions or CPU. I wanted to give flexibility to the consumer of Machine to choose which is appropriate for their application. This is also true of Tensorflow.
</blockquote></details>

Created a new "docker" group in poetry.  This will allow the specific packages to be called out when creating the docker images, both for the devenv and for the prod docker image.
___
*[`pyproject.toml` line 87 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_yKyCIHEyDOxL0Sp:-NXqRRXW8Ot9dqzh36NB:b2rlvf9) ([raw file](https://github.com/sillsdev/machine.py/blob/17c016f9025bd3e922f26175696160a1ba1a7a2d/pyproject.toml#L87)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Sentencepiece was moved to a main install.  I moved it to the docker extras.
</blockquote></details>

correction - I misunderstood how extras work.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/15)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`pyproject.toml` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpZn-r2Rh2JiTZXiCA:-NXsK4eh2VqbGfewnkEa:brkg9i3) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L71)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Created a new "docker" group in poetry.  This will allow the specific packages to be called out when creating the docker images, both for the devenv and for the prod docker image.
</blockquote></details>

I don't see where the "docker" group is defined.
___
*[`pyproject.toml` line 75 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWp_qBSDgSTB9sRll6X:-NXsKVr15rFlOtjSgQx5:bwc8c19) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L75)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I disagree - Datasets is used in train in HuggingFaceNmtModelTrainer.  How can we run it without it?
</blockquote></details>

You are correct. It should be included in the "huggingface" extra.
___
*[`pyproject.toml` line 92 at r2](https://reviewable.io/reviews/sillsdev/machine.py/15#-NXsLydk0liMMVAF3fEj:-NXsLydk0liMMVAF3fEk:b-4x2j95) ([raw file](https://github.com/sillsdev/machine.py/blob/e660273a0779ba6a5998024d59b2f2d0d96a6c66/pyproject.toml#L92)):*
> ```TOML
> thot = ["sil-thot"]
> jobs = ["clearml", "json-stream", "dynaconf"]
> all_but_nmt = ["sentencepiece","sil-thot", "jobs"]
> ```

This extra is unnecessary. You can specify multiple extras when you install the package.
___
*[`pyproject.toml` line 93 at r2](https://reviewable.io/reviews/sillsdev/machine.py/15#-NXsLG56EKByiB8KZASE:-NXsLG56EKByiB8KZASF:b-z5otn7) ([raw file](https://github.com/sillsdev/machine.py/blob/e660273a0779ba6a5998024d59b2f2d0d96a6c66/pyproject.toml#L93)):*
> ```TOML
> jobs = ["clearml", "json-stream", "dynaconf"]
> all_but_nmt = ["sentencepiece","sil-thot", "jobs"]
> all_huggingface = ["all_but_nmt","torch","transformers", "sacremoses","datasets","accelerate"]
> ```

Please change the names of the extras back to what they were. There isn't a need to change them.

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpZn-r2Rh2JiTZXiCA:-NXtkNfr3K2aiI6N_6-c:beg2ffb) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L71)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't see where the "docker" group is defined.
</blockquote></details>

Putting the format back to your original format.

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 93 at r2](https://reviewable.io/reviews/sillsdev/machine.py/15#-NXsLG56EKByiB8KZASE:-NXtkq758UsLMEBA-WEi:byuxkfp) ([raw file](https://github.com/sillsdev/machine.py/blob/e660273a0779ba6a5998024d59b2f2d0d96a6c66/pyproject.toml#L93)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please change the names of the extras back to what they were. There isn't a need to change them.
</blockquote></details>

Reverting to your format - calling out intermediate packages.

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 71 at r1](https://reviewable.io/reviews/sillsdev/machine.py/15#-NWpZn-r2Rh2JiTZXiCA:-NXu3Lez5YNXcVMb4pgc:b2aoxbv) ([raw file](https://github.com/sillsdev/machine.py/blob/e92e3c05d46a4c047530a0024f67965f053af668/pyproject.toml#L71)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Putting the format back to your original format.
</blockquote></details>

Correction - grouped by extras.  The extras was not working at all before - they need to be optional in the main dependencies section.  With the refactoring, I believe it is actually working now.

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 92 at r2](https://reviewable.io/reviews/sillsdev/machine.py/15#-NXsLydk0liMMVAF3fEj:-NXu3b8I0E7JWSH54sM2:b-vcttq9) ([raw file](https://github.com/sillsdev/machine.py/blob/e660273a0779ba6a5998024d59b2f2d0d96a6c66/pyproject.toml#L92)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Reverting to your format.
</blockquote></details>

Correction - this would not work anyway - see other comments for updates.

**Review by ddaspit — APPROVED** [review]
This looks good. Thanks for figuring out all of the poetry stuff.

> Reviewed 1 of 4 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/15#-:-NXxtofJ5QTvO8BwU92d:bj1sn53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
