### PR TITLE
Update machine.py to reflect usfm changes in machine

### PR DESCRIPTION
**Pull request by mshannon-sil**
Based on the changes in Machine from https://github.com/sillsdev/machine/pull/160, I've updated machine.py's handling of USFM accordingly.

Main changes:
1. Files in `machine/corpora` were either created or modified to align with new files/changes in Machine
2. `Versification.load()` in `machine/scripture/verse_ref.py` was updated to accept a stream as input, like it can in Machine
3. Test files were created or modified to reflect new test files/changes in Machine
4. I added a new test case `test_utf_16_encoding_stream()` in `tests/scripture/test_versification.py` to test code I added which handles Unicode errors for loading versification from a stream.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/103)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/103)* status: all files reviewed, 8 unresolved discussions (waiting on @mshannon-sil)

___
*[`machine/corpora/paratext_backup_terms_corpus.py` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0XgMF8jvxjidZ2Yla:-Nu0XgMF8jvxjidZ2Ylb:b5byynh) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_backup_terms_corpus.py#L15)):*
> ```Python
> class ParatextBackupTermsCorpus(DictionaryTextCorpus):
>     def __init__(self, filename: str, term_categories: List[str]) -> None:
>         self._predefined_terms_list_types = ["Major", "All", "SilNt", "Pt6"]
> ```

You can move this to a constant (`_PREDEFINED_TERMS_LIST_TYPES`) at the top of the file.
___
*[`machine/corpora/paratext_backup_terms_corpus.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0YQ795d9R-T-4XuRw:-Nu0YQ795d9R-T-4XuRx:bnp3p8g) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_backup_terms_corpus.py#L61)):*
> ```Python
>             self._add_text(text)
> 
>     def _get_renderings(self, rendering: str) -> List[str]:
> ```

You can refactor these methods to functions at the top level of the file. Generally, I port any private static methods to module-level "private" functions.
___
*[`machine/corpora/paratext_project_settings.py` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0V8mnBwJwrIuRhQCg:-Nu0V8mnBwJwrIuRhQCh:bkhe427) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_project_settings.py#L7)):*
> ```Python
> 
> 
> class ParatextProjectSettings(ABC):
> ```

This can be a dataclass.
___
*[`machine/corpora/paratext_project_settings_parser_base.py` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0VlmN2zDgy2e4n3PE:-Nu0VlmN2zDgy2e4n3PF:b-7qopgk) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_project_settings_parser_base.py#L15)):*
> ```Python
> 
>     @abstractmethod
>     def __enter__(self) -> "ParatextProjectSettingsParserBase": ...
> ```

I don't think this class needs to be a context manager.
___
*[`machine/corpora/zip_paratext_project_settings_parser.py` line 20 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0XDSy8z8oHLAoYuXz:-Nu0XDSy8z8oHLAoYuY-:b-z053i7) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/zip_paratext_project_settings_parser.py#L20)):*
> ```Python
>         return file_name in self._archive.namelist()
> 
>     def find(self, extension: str) -> Union[str, None]:
> ```

`Optional[str]` is better than `Union[str, None]`.
___
*[`machine/corpora/zip_paratext_project_settings_parser_base.py` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0WzAm7TQ2j0vjD4dh:-Nu0WzAm7TQ2j0vjD4di:b-cgsi98) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/zip_paratext_project_settings_parser_base.py#L15)):*
> ```Python
>                     stylesheet_temp_file.write(source.read())
>                 stylesheet_path = stylesheet_temp_file.name
>             custom_stylesheet_path = None
> ```

You forgot to specify the type here.
___
*[`tests/corpora/test_usfm_verse_text_updater.py` line 5 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0_3nHEgy-Y91Uos_o:-Nu0_3nHEgy-Y91Uos_p:b8tz6w) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/tests/corpora/test_usfm_verse_text_updater.py#L5)):*
> ```Python
> from testutils.corpora_test_helpers import USFM_TEST_PROJECT_PATH
> 
> from machine.corpora.usfm_parser import parse_usfm
> ```

You should import from the package, i.e. `from machine.corpora import parse_usfm`.
___
*[`tests/corpora/test_usfm_verse_text_updater.py` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0_C8c00aaajr3glAT:-Nu0_C8c00aaajr3glAU:b-33rc6x) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/tests/corpora/test_usfm_verse_text_updater.py#L13)):*
> ```Python
>     rows = [
>         (
>             [VerseRef.from_string("MAT 1:1", Versification.get_builtin(VersificationType.ENGLISH))],
> ```

You can import the versification as a constant from `machine.scripture`, i.e. `from machine.scripture import ENGLISH_VERSIFICATION`.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/103)* status: 13 of 21 files reviewed, 8 unresolved discussions (waiting on @ddaspit and @mshannon-sil)

___
*[`machine/corpora/paratext_backup_terms_corpus.py` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0XgMF8jvxjidZ2Yla:-Nu0h0Uy57ugVOOtdss2:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_backup_terms_corpus.py#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can move this to a constant (`_PREDEFINED_TERMS_LIST_TYPES`) at the top of the file.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_backup_terms_corpus.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0YQ795d9R-T-4XuRw:-Nu5g_XP2K3LFZrOa_rT:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_backup_terms_corpus.py#L61)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can refactor these methods to functions at the top level of the file. Generally, I port any private static methods to module-level "private" functions.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_project_settings.py` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0V8mnBwJwrIuRhQCg:-Nu5i7CpE6c2UiEbEkT1:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_project_settings.py#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This can be a dataclass.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_project_settings_parser_base.py` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0VlmN2zDgy2e4n3PE:-Nu5rf1Y-CzcJvbsmKIN:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_project_settings_parser_base.py#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this class needs to be a context manager.
</blockquote></details>

Done.
___
*[`machine/corpora/zip_paratext_project_settings_parser.py` line 20 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0XDSy8z8oHLAoYuXz:-Nu5rxQA76ETNJmVt9dC:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/zip_paratext_project_settings_parser.py#L20)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`Optional[str]` is better than `Union[str, None]`.
</blockquote></details>

Done.
___
*[`machine/corpora/zip_paratext_project_settings_parser_base.py` line 15 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0WzAm7TQ2j0vjD4dh:-Nu5uCZQEoQo6eL8dgBZ:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/zip_paratext_project_settings_parser_base.py#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to specify the type here.
</blockquote></details>

Done.
___
*[`tests/corpora/test_usfm_verse_text_updater.py` line 5 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0_3nHEgy-Y91Uos_o:-Nu5vJtnB3ut0lVMzS7C:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/tests/corpora/test_usfm_verse_text_updater.py#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should import from the package, i.e. `from machine.corpora import parse_usfm`.
</blockquote></details>

Done.
___
*[`tests/corpora/test_usfm_verse_text_updater.py` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0_C8c00aaajr3glAT:-Nu5zN4m8nSGLUe_vPMC:b-37vnxt) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/tests/corpora/test_usfm_verse_text_updater.py#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can import the versification as a constant from `machine.scripture`, i.e. `from machine.scripture import ENGLISH_VERSIFICATION`.
</blockquote></details>

Done. Also, there's a handful of other places in the codebase that use `Versification.get_builtin(VersificationType.ENGLISH)` rather than `ENGLISH_VERSIFICATION`. Would you like me to change those too so that it's consistent?

**Comment by mshannon-sil** [comment]
This PR is porting over the changes from https://github.com/sillsdev/machine/pull/163 as well now.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/103)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`machine/corpora/paratext_project_settings.py` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0V8mnBwJwrIuRhQCg:-NuZkiDaB4sjrAiAYgwA:b-odz4xo) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_project_settings.py#L7)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think it needs to be an abstract base class.
___
*[`tests/corpora/test_usfm_verse_text_updater.py` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0_C8c00aaajr3glAT:-NuZl0kK4EBqmWMmtlxs:b-x4kg7v) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/tests/corpora/test_usfm_verse_text_updater.py#L13)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Done. Also, there's a handful of other places in the codebase that use `Versification.get_builtin(VersificationType.ENGLISH)` rather than `ENGLISH_VERSIFICATION`. Would you like me to change those too so that it's consistent?
</blockquote></details>

I believe that there are a couple of places that need to use ``Versification.get_builtin()`, but other than that everywhere else should use the constants.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/103)* status: 19 of 25 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @mshannon-sil)

___
*[`machine/corpora/paratext_project_settings.py` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0V8mnBwJwrIuRhQCg:-NudYeZP-TyN2jC-XfaM:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/machine/corpora/paratext_project_settings.py#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think it needs to be an abstract base class.
</blockquote></details>

Done.
___
*[`tests/corpora/test_usfm_verse_text_updater.py` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine.py/103#-Nu0_C8c00aaajr3glAT:-NudYfwL3vQr_PS2w97Y:b-h19ius) ([raw file](https://github.com/sillsdev/machine.py/blob/46f5e4dd733687951662b1158007c06e71b5963c/tests/corpora/test_usfm_verse_text_updater.py#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I believe that there are a couple of places that need to use ``Versification.get_builtin()`, but other than that everywhere else should use the constants.
</blockquote></details>

Okay, I changed most of the places that I saw using `Versification.get_builtin(VersificationType.ENGLISH)` to use `ENGLISH_VERSIFICATION` instead, except in verse_ref.py to avoid circular imports. All the test cases are still passing. Let me know if there's any of those places that I need to change back to the original method.

**Pull request merged**
