### PR TITLE
Alignment Job

### PR DESCRIPTION
**Pull request by johnml1135**
Add an SMT alignment job
This lays the groundwork for https://github.com/sillsdev/serval/issues/410.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/114)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
I added several comments about adding more separation between MT and alignment builds. Generally, DRY is a good principle to follow, but, in this instance, MT and alignment are different tasks that have different inputs/outputs, requirements, settings, dependencies, etc. and will most likely need to evolve separately from each other. I don't really have an issue if the MT classes and alignment classes have some similar code. 

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/114#-:-O4gMIO4ARbooh1E5ex5:b-w6nwlw)* status: all files reviewed, 8 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/build_word_alignment_model.py` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gAWcd-VHL79bZS3ep:-O4gAWcd-VHL79bZS3eq:br7h3nl) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/build_word_alignment_model.py#L7)):*
> ```Python
> from clearml import Task
> 
> from machine.jobs.thot.thot_word_alignment_model_factory import ThotWordAlignmentModelFactory
> ```

This should be a relative import.
___
*[`machine/jobs/engine_build_job.py` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gJDwJAVwGYHeveIs2:-O4gJDwJAVwGYHeveIs3:b-d1orzx) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/engine_build_job.py#L13)):*
> ```Python
> 
> 
> class EngineBuildJob(ABC):
> ```

I don't know how much this class buys us, since it doesn't really have any logic in it. It just provides a skeleton. I am also not a big fan of passing variables between methods using class fields. It makes the dependencies between the methods less explicit and more error-prone. If we do use this class, we should provide different implementations for MT and word alignment.
___
*[`machine/jobs/engine_build_job.py` line 47 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gAqzLAIcf2ep_bcQs:-O4gAqzM88h3fI4c2kOW:b-r2l1ii) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/engine_build_job.py#L47)):*
> ```Python
> 
>     @abstractmethod
>     def start_job(self) -> None: ...
> ```

All of these "protected" methods should be prefixed with an underscore.
___
*[`machine/jobs/nmt_engine_build_job.py` line 113 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gDfhx2LnfSmIQLtwZ:-O4gDfhy6IFkFPUbUr7x:b-mov2ef) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/nmt_engine_build_job.py#L113)):*
> ```Python
>     for i, result in enumerate(engine.translate_batch(source_segments)):
>         batch[i]["translation"] = result.translation
>         writer.write(batch[i])  # type: ignore
> ```

Why are you ignoring the type checking here?
___
*[`machine/jobs/settings.yaml` line 30 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gE9JZ66hTuugYsb3m:-O4gE9JZ66hTuugYsb3n:b-281ssk) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/settings.yaml#L30)):*
> ```YAML
>   thot:
>     word_alignment_model_type: hmm
>     word_alignment_heuristic: grow-diag-final-and
> ```

We will probably want different settings for the SMT engine and the word alignment models. We should add a new section, maybe `thot_align`.
___
*[`machine/jobs/shared_file_service.py` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gHXIh7M1yb2f85bG2:-O4gHXIh7M1yb2f85bG3:bie8hri) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/shared_file_service.py#L41)):*
> ```Python
> 
> 
> class SharedFileService(ABC):
> ```

I would define separate classes for MT and word alignment. You can still define a base class if there is some shared code.
___
*[`machine/jobs/smt_model_factory.py` line 14 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gI1P45paUdeAPcQ0S:-O4gI1P45paUdeAPcQ0T:b-5l1wbl) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/smt_model_factory.py#L14)):*
> ```Python
> 
> 
> class SmtModelFactory(ABC, ThotModelFactory):
> ```

The `SmtModelFactory` class is intended to be decoupled from any specific SMT implementation, such as Thot. Also, you should define a separate word alignment model factory.
___
*[`machine/jobs/word_alignment_build_job.py` line 84 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gM8cCBCSO8ZDupsBi:-O4gM8cCBCSO8ZDupsBj:b6z0nmp) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/word_alignment_build_job.py#L84)):*
> ```Python
>                         row_count=alignment.row_count,
>                         alignment=str(alignment),
>                     )  # type: ignore
> ```

What is type checking being ignored here?

**Comment by johnml1135** [comment]
*[`machine/jobs/build_word_alignment_model.py` line 7 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gAWcd-VHL79bZS3ep:-O4jlQM7AJ4t6E1Rh8P-:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/build_word_alignment_model.py#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be a relative import.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`machine/jobs/engine_build_job.py` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gJDwJAVwGYHeveIs2:-O4jtId04OW4-NKrElGE:bnfcisn) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/engine_build_job.py#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't know how much this class buys us, since it doesn't really have any logic in it. It just provides a skeleton. I am also not a big fan of passing variables between methods using class fields. It makes the dependencies between the methods less explicit and more error-prone. If we do use this class, we should provide different implementations for MT and word alignment.
</blockquote></details>

Renamed to TranslationEngineBuildJob - and removed it from WordAlignmentBuildJob.

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 113 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gDfhx2LnfSmIQLtwZ:-O4jw0_eECFYh_oLW3B8:b9lpf2x) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/nmt_engine_build_job.py#L113)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why are you ignoring the type checking here?
</blockquote></details>

Changed the typing check for write - to just look for an object.

**Comment by johnml1135** [comment]
*[`machine/jobs/shared_file_service.py` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gHXIh7M1yb2f85bG2:-O4l-RMr4SjyCM3s8oEj:b-uocu71) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/shared_file_service.py#L41)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would define separate classes for MT and word alignment. You can still define a base class if there is some shared code.
</blockquote></details>

Ugh - took a while.

**Comment by johnml1135** [comment]
*[`machine/jobs/word_alignment_build_job.py` line 84 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gM8cCBCSO8ZDupsBi:-O4lE1iq3tzLJlRGX_YO:b-40afml) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/word_alignment_build_job.py#L84)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is type checking being ignored here?
</blockquote></details>

There was a typo - I found it and it resolved the core issue.

**Comment by johnml1135** [comment]
*[`machine/jobs/smt_model_factory.py` line 14 at r1](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4gI1P45paUdeAPcQ0S:-O4lRoRaAXNWo0teiv2x:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/e66e50712e119499d49b916660bc8578d0dcfe20/machine/jobs/smt_model_factory.py#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `SmtModelFactory` class is intended to be decoupled from any specific SMT implementation, such as Thot. Also, you should define a separate word alignment model factory.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
This is looking really good. I have a couple more comments.

> Reviewed 25 of 27 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/114#-:-O4r5TXzEwecmevxxV4B:b7nd2zh)* status: all files reviewed, 9 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/build_nmt_engine.py` line 61 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r0ci3Bi8lM0tHltRk:-O4r0ci3Bi8lM0tHltRl:b-tl9ccs) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/build_nmt_engine.py#L61)):*
> ```Python
>         logger.info(f"Config: {SETTINGS.as_dict()}")
> 
>         translation_file_service = TranslationFileService("ClearML", SETTINGS)
> ```

It would be better to use the enum value for the type instead of the string.
___
*[`machine/jobs/build_word_alignment_model.py` line 58 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r0wFEAi7YkDnmZaU2:-O4r0wFEAi7YkDnmZaU3:b-tl9ccs) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/build_word_alignment_model.py#L58)):*
> ```Python
>         logger.info(f"Config: {SETTINGS.as_dict()}")
> 
>         word_alignment_file_service = WordAlignmentFileService("ClearML", SETTINGS)
> ```

It would be better to use the enum value for the type instead of the string.
___
*[`machine/jobs/translation_file_service.py` line 7 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qVNkW-w0htgrFmEeh:-O4qVNkX8gXAUywh6xrI:bk37uwd) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/translation_file_service.py#L7)):*
> ```Python
> import json_stream
> 
> from machine.jobs.shared_file_service_base import DictToJsonWriter, SharedFileServiceBase
> ```

You missed a couple of relative imports.
___
*[`machine/jobs/translation_file_service.py` line 25 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r15AY2d2ba8H-A-xF:-O4r15AY2d2ba8H-A-xG:bdfhxv8) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_file_service.py#L25)):*
> ```Python
>     def __init__(
>         self,
>         type: Union[str, SharedFileServiceType],
> ```

Do we need to support a string value? Just the enum should be sufficient.
___
*[`machine/jobs/word_alignment_build_job.py` line 55 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r3kPL0bzEUAWPh149:-O4r3kPL0bzEUAWPh14A:b-fxm4m9) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/word_alignment_build_job.py#L55)):*
> ```Python
>     def _init_corpus(self) -> None:
>         logger.info("Downloading data files")
>         if "_source_corpus" not in self.__dict__:
> ```

See my comment in the `TranslationEngineBuildJob` class.
___
*[`machine/jobs/thot/thot_word_alignment_model_factory.py` line 18 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qW-ty4Ahd07opr5aE:-O4qW-ty4Ahd07opr5aF:b-g4k3nv) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/thot/thot_word_alignment_model_factory.py#L18)):*
> ```Python
> class ThotWordAlignmentModelFactory(WordAlignmentModelFactory):
>     def init(self) -> None:
>         shutil.copytree(_THOT_NEW_MODEL_DIRECTORY, self._model_dir, dirs_exist_ok=True)
> ```

We will probably want a different new model template for word alignment models. The SMT template contains many files that are specific to SMT models. Should I provide you with a new alignment model template?
___
*[`machine/jobs/thot/thot_word_alignment_model_factory.py` line 42 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qWQk87ic6lu9qSYoX:-O4qWQk87ic6lu9qSYoY:bwa9a9v) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/thot/thot_word_alignment_model_factory.py#L42)):*
> ```Python
>     ) -> WordAlignmentModel:
>         model = ThotSymmetrizedWordAlignmentModel(
>             create_thot_word_alignment_model(self._config.thot.word_alignment_model_type, self._direct_model_path),
> ```

You should use the model type from the `thot_align` section.
___
*[`machine/tokenization/tokenizer_factory.py` line 28 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qWmfz03YsC5mGthHo:-O4qWmfz03YsC5mGthHp:b726pr8) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/tokenization/tokenizer_factory.py#L28)):*
> ```Python
> 
> 
> def create_tokenizer(type: Union[str, TokenizerType]) -> Tokenizer[str, int, str]:
> ```

These functions should be exported from the `tokenization` package.
___
*[`machine/jobs/translation_engine_build_job.py` line 51 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r2MU14zjZmeI-GF3z:-O4r2MU14zjZmeI-GF4-:bp1yyj2) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_engine_build_job.py#L51)):*
> ```Python
>     def _init_corpus(self) -> None:
>         logger.info("Downloading data files")
>         if "_source_corpus" not in self.__dict__:
> ```

This is hacky. As I stated before, there are issues with passing parameters between methods using class fields. You can create these objects at the beginning of the `run` method and pass them as parameters to the appropriate methods.

**Comment by johnml1135** [comment]
*[`machine/jobs/build_nmt_engine.py` line 61 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r0ci3Bi8lM0tHltRk:-O4vzm2GEyvciBP0XWmh:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/build_nmt_engine.py#L61)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be better to use the enum value for the type instead of the string.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`machine/jobs/build_word_alignment_model.py` line 58 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r0wFEAi7YkDnmZaU2:-O4w-4R37DiiIb1ipuc9:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/build_word_alignment_model.py#L58)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be better to use the enum value for the type instead of the string.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`machine/jobs/translation_engine_build_job.py` line 51 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r2MU14zjZmeI-GF3z:-O5-_kzD7Xz5l85h_SY6:b-197fcx) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_engine_build_job.py#L51)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is hacky. As I stated before, there are issues with passing parameters between methods using class fields. You can create these objects at the beginning of the `run` method and pass them as parameters to the appropriate methods.
</blockquote></details>

I moved them to properties.  That appears more pythonic and saves having to move the source, target and parallel corpuses around.

**Comment by johnml1135** [comment]
*[`machine/jobs/translation_file_service.py` line 7 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qVNkW-w0htgrFmEeh:-O5-aN6lDbFAqy2MSdp-:bf8c61m) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/translation_file_service.py#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You missed a couple of relative imports.
</blockquote></details>

Found all and fixed them all.

**Comment by johnml1135** [comment]
*[`machine/jobs/translation_file_service.py` line 25 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r15AY2d2ba8H-A-xF:-O5-caKTD1b-OOMs_KYM:ba9iplf) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_file_service.py#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do we need to support a string value? Just the enum should be sufficient.
</blockquote></details>

Changed to constants.

**Comment by johnml1135** [comment]
*[`machine/jobs/word_alignment_build_job.py` line 55 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r3kPL0bzEUAWPh149:-O5-ce0q2Z2jc4jCmNll:b46bxtz) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/word_alignment_build_job.py#L55)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my comment in the `TranslationEngineBuildJob` class.
</blockquote></details>

Also updated.

**Comment by johnml1135** [comment]
*[`machine/jobs/thot/thot_word_alignment_model_factory.py` line 18 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qW-ty4Ahd07opr5aE:-O5-ckuk5V1-rGCM71zb:b-7lgo1y) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/thot/thot_word_alignment_model_factory.py#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We will probably want a different new model template for word alignment models. The SMT template contains many files that are specific to SMT models. Should I provide you with a new alignment model template?
</blockquote></details>

Yes, please.  I wouldn't know what was needed (unless I spent many hours).

**Comment by johnml1135** [comment]
*[`machine/jobs/thot/thot_word_alignment_model_factory.py` line 42 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qWQk87ic6lu9qSYoX:-O5-fQ7BBXGzEBOabCd0:b20sf5l) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/thot/thot_word_alignment_model_factory.py#L42)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should use the model type from the `thot_align` section.
</blockquote></details>

Done - and changed it over for the tokenizer as well.

**Comment by johnml1135** [comment]
I believe the last thing is the new word alignment template.

**Comment by johnml1135** [comment]
*[`machine/tokenization/tokenizer_factory.py` line 28 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qWmfz03YsC5mGthHo:-O5-hzp5AtFzXXtx4JQY:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/tokenization/tokenizer_factory.py#L28)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These functions should be exported from the `tokenization` package.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 16 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/114)* status: 36 of 37 files reviewed, 5 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/build_word_alignment_model.py` line 88 at r4](https://reviewable.io/reviews/sillsdev/machine.py/114#-O5FnAwE9PIzabXBczcL:-O5FnAwE9PIzabXBczcM:b-e0xrn4) ([raw file](https://github.com/sillsdev/machine.py/blob/f21a13074d4b113bc85f0b3cbc651d9a0df4f3da/machine/jobs/build_word_alignment_model.py#L88)):*
> ```Python
>         if scheduler is not None:
>             scheduler.stop()
>     return word_alignment_build_job
> ```

This return value doesn't seem to be used anywhere. Are you returning this intentionally?
___
*[`machine/jobs/translation_file_service.py` line 25 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r15AY2d2ba8H-A-xF:-O5FtZii42W6PsSSaEwD:briznep) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_file_service.py#L25)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Changed to constants.
</blockquote></details>

The constants are a good change. I was actually referring to the `type` parameter. I don't think we need to accept a `str`.
___
*[`machine/jobs/translation_engine_build_job.py` line 51 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r2MU14zjZmeI-GF3z:-O5Fo1Gf133O5P6JDhNN:bkqlm9s) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_engine_build_job.py#L51)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I moved them to properties.  That appears more pythonic and saves having to move the source, target and parallel corpuses around.
</blockquote></details>

The `create_source_corpus` and `create_target_corpus` methods actually download files from the S3 bucket. It would be unexpected behavior and a code smell for a property to perform long-running processing. Also, you shouldn't reference fields by their name, since this can easily result in a bug if the field name is ever changed. The easiest way forward is to remove this class and create the corpora in the `run` method of the `SmtEngineBuildJob` and `NmtEngineBuildJob` classes. This class adds complexity without adding much value.  The other option is to create the corpora at the beginning of the `run` method and pass the variables to the appropriate methods.

**Comment by johnml1135** [comment]
*[`machine/jobs/build_word_alignment_model.py` line 88 at r4](https://reviewable.io/reviews/sillsdev/machine.py/114#-O5FnAwE9PIzabXBczcL:-O5Ij7vIDztmUKnu1M_P:b-5c34ao) ([raw file](https://github.com/sillsdev/machine.py/blob/f21a13074d4b113bc85f0b3cbc651d9a0df4f3da/machine/jobs/build_word_alignment_model.py#L88)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This return value doesn't seem to be used anywhere. Are you returning this intentionally?
</blockquote></details>

It's still a work in progress - I'll make a few more changes.

**Comment by johnml1135** [comment]
*[`machine/jobs/build_word_alignment_model.py` line 88 at r4](https://reviewable.io/reviews/sillsdev/machine.py/114#-O5FnAwE9PIzabXBczcL:-O5IzLS_3qp8pRgX1TaZ:b-vce5pb) ([raw file](https://github.com/sillsdev/machine.py/blob/f21a13074d4b113bc85f0b3cbc651d9a0df4f3da/machine/jobs/build_word_alignment_model.py#L88)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It's still a work in progress - I'll make a few more changes.
</blockquote></details>

I'm slimming it down a bit.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/114)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/settings.yaml` line 31 at r5](https://reviewable.io/reviews/sillsdev/machine.py/114#-O5JjKJ-B1Phr8Lnt8tJ:-O5JjKJ-B1Phr8Lnt8tK:b-q5uga4) ([raw file](https://github.com/sillsdev/machine.py/blob/a86f614a842fd92ecaccf7c8e7762fa41491f24f/machine/jobs/settings.yaml#L31)):*
> ```YAML
>     word_alignment_model_type: hmm
>     tokenizer: latin
>   thot_align:
> ```

I know I told you to create a `thot_align` section, but I'm still not happy with the way that the settings are structured. I don't think the section names are clear enough. What about if we change the `thot` and `huggingface` sections to `thot_mt` and `huggingface_mt`. That would clearly differentiate the MT configs from the alignment configs. Or we could have separate `mt` and `align` sections under the `thot` section.
___
*[`machine/jobs/translation_file_service.py` line 25 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r15AY2d2ba8H-A-xF:-O5JgF6q6kyOUlGHMHHh:b-8riji) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_file_service.py#L25)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I believe that we need to based upon them being defined in SETTINGS.
</blockquote></details>

It looks like all calls to the `TranslationFileService` constructor pass a `SharedFileServiceType` enum value. A `str` value is never passed.
___
*[`machine/jobs/thot/thot_word_alignment_model_factory.py` line 18 at r2](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4qW-ty4Ahd07opr5aE:-O5JiDlz-6zCb2tSl_pC:b-2k5m3i) ([raw file](https://github.com/sillsdev/machine.py/blob/9eb6c7f270ad849a7ffbac31bcc654afbff6f148/machine/jobs/thot/thot_word_alignment_model_factory.py#L18)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes, please.  I wouldn't know what was needed (unless I spent many hours).
</blockquote></details>

Now that I think about it, I don't think we need a new model template. You can just remove the `init` method altogether.

**Comment by johnml1135** [comment]
*[`machine/jobs/settings.yaml` line 31 at r5](https://reviewable.io/reviews/sillsdev/machine.py/114#-O5JjKJ-B1Phr8Lnt8tJ:-O5NjaAKBOpTCmtEl9fF:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/a86f614a842fd92ecaccf7c8e7762fa41491f24f/machine/jobs/settings.yaml#L31)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I know I told you to create a `thot_align` section, but I'm still not happy with the way that the settings are structured. I don't think the section names are clear enough. What about if we change the `thot` and `huggingface` sections to `thot_mt` and `huggingface_mt`. That would clearly differentiate the MT configs from the alignment configs. Or we could have separate `mt` and `align` sections under the `thot` section.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`machine/jobs/translation_file_service.py` line 25 at r3](https://reviewable.io/reviews/sillsdev/machine.py/114#-O4r15AY2d2ba8H-A-xF:-O5NqwBl49KRugwY6LB_:bsbiaxy) ([raw file](https://github.com/sillsdev/machine.py/blob/ba87dfc2c84e27b9b36c251dd2159d56b748399b/machine/jobs/translation_file_service.py#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like all calls to the `TranslationFileService` constructor pass a `SharedFileServiceType` enum value. A `str` value is never passed.
</blockquote></details>

Yes - you are right.  It has to do with what calls it, not the underlying settings.  Updated for both.

**Review by ddaspit — APPROVED** [review]
Good job.

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/114#-:-O5OgpNz-x33uuSoVM7I:b-ul7oq9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
