### PR TITLE
Percent complete try2

### PR DESCRIPTION
**Pull request by johnml1135**
Add inference_steps, num_steps as scalars.  To resolve https://github.com/sillsdev/serval/issues/44

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/41)

### CODE REVIEW

**Comment by Enkidu93** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 73 at r1](https://reviewable.io/reviews/sillsdev/machine.py/41#-NgZTzAREvpKLHxnci6O:-NgZTzASB1SQn3w-_bdQ:bk6cbzc) ([raw file](https://github.com/sillsdev/machine.py/blob/4a655d8316d40c6422671bc3f1f5076554e32ef3/machine/jobs/nmt_engine_build_job.py#L73)):*
> ```Python
>     def _send_clearml_config(self) -> None:
>         if self.clearml_task:
>             self.clearml_task.get_logger().report_single_value(name="total_steps", value=self._config["max_steps"])
> ```

As long as this is logged as other values are and is accessible via the ClearML API in the same way, I should be good to go. I haven't worked with machine.py, so I can't comment intelligently on the rest.

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Comment by Enkidu93** [comment]
@johnml1135 You said the inference updates still aren't working?

**Comment by johnml1135** [comment]
I fixed it.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/41)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 23 at r2](https://reviewable.io/reviews/sillsdev/machine.py/41#-Ng_FQQh-3cCXwMv1Oby:-Ng_FQQh-3cCXwMv1Obz:bqwv4kn) ([raw file](https://github.com/sillsdev/machine.py/blob/cb0aaa078901751e8486fe9372dce8375eaaa919/machine/jobs/nmt_engine_build_job.py#L23)):*
> ```Python
>         self.clearml_task: Optional[Task] = None
> 
>     def run(self, task: Optional[Task] = None) -> None:
> ```

I was specifically trying to avoid any dependencies on ClearML in this class. I would pass in a callback function for reporting progress.
___
*[`machine/translation/thot/thot_smt_model_trainer.py` line 63 at r2](https://reviewable.io/reviews/sillsdev/machine.py/41#-Ng_GEwREzJ_dwUI9X3A:-Ng_GEwREzJ_dwUI9X3B:b-wge903) ([raw file](https://github.com/sillsdev/machine.py/blob/cb0aaa078901751e8486fe9372dce8375eaaa919/machine/translation/thot/thot_smt_model_trainer.py#L63)):*
> ```Python
>         while chunk != b"":
>             entry = struct.unpack(chunk)
>             entries.append(entry[:-1])  # type: ignore
> ```

What is the typing issue here?

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 23 at r2](https://reviewable.io/reviews/sillsdev/machine.py/41#-Ng_FQQh-3cCXwMv1Oby:-Ng_U7I16PefY0rW1k-c:babllmc) ([raw file](https://github.com/sillsdev/machine.py/blob/cb0aaa078901751e8486fe9372dce8375eaaa919/machine/jobs/nmt_engine_build_job.py#L23)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I was specifically trying to avoid any dependencies on ClearML in this class. I would pass in a callback function for reporting progress.
</blockquote></details>

We will also need functions for updating inference status, etc.  Either we pass 2-3 functions, or we pass the task (or a null).

**Review by ddaspit — COMMENTED** [review]
I think I have a good approach for handling the progress. We can pass in a progress callback to `NmtEngineBuildJob.run` that calls the ClearML logger to update the percent completed. We can then use the `PhasedProgressReporter` class with two phases: training and inferencing. We pass in the `PhaseProgress` for the training phase to the `model_trainer.train` call. That way we will no longer need the `ClearMLCallback` and the monkey patch that goes along with it. We then use the `PhaseProgress` for the inferencing phase to update the progress as we translate verses. I can take over the branch to implement this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/41#-:-Ng_S83aApEXWZpNdl1p:btkltib)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

**Comment by johnml1135** [comment]
*[`machine/translation/thot/thot_smt_model_trainer.py` line 63 at r2](https://reviewable.io/reviews/sillsdev/machine.py/41#-Ng_GEwREzJ_dwUI9X3A:-Ng_UFskAKouflpYqzf0:b-5fi98d) ([raw file](https://github.com/sillsdev/machine.py/blob/cb0aaa078901751e8486fe9372dce8375eaaa919/machine/translation/thot/thot_smt_model_trainer.py#L63)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is the typing issue here?
</blockquote></details>

I think pyright was squalking.

**Comment by johnml1135** [comment]
If you really think it needs implemented substantively differently, then do it.  I think this is clear and clean enough for what we want to accomplish.  We will also need to report back the max_steps, as Machine will no longer inherently know it (and is needed for % complete estimations).

**Review by ddaspit — COMMENTED** [review]
I updated the implementation so that it computes and reports the percent completed. It should be straightforward to update Machine to retrieve the `progress` metric.

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/41#-:-NgdjyxLDzq0ejzD6BVi:by7azz1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/41#-:-NgdkVubCDh3M5snrPLj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
