### PR TITLE
Port USFM code from Machine up to commit bf2b46d

### PR DESCRIPTION
**Pull request by mshannon-sil**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115)

### CODE REVIEW

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115)* status: 0 of 22 files reviewed, 1 unresolved discussion

___
*[`machine/corpora/paratext_project_settings.py` line 23 at r4](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4XujN10nte1IwrTQyP:-O4XujN10nte1IwrTQyQ:b-1b7aar) ([raw file](https://github.com/sillsdev/machine.py/blob/3c670cc90cd934ebc2c1639cab34cccf63bae6c7/machine/corpora/paratext_project_settings.py#L23)):*
> ```Python
>     biblical_terms_file_name: str
> 
>     def get_book_id(self, file_name: str) -> Optional[str]:
> ```

This is called `IsBookFileName` in Machine, and it returns a bool as well as an output parameter of `string bookId`. I could have had the machine.py version return a tuple with a bool and a str, but returning the bool seemed unnecessary since whenever the bool is false, the `bookId` is null, so we can just check that `book_id` isn't falsy in python. And since it no longer returns a bool, I renamed the method to `get_book_id` to align with what it's doing. However, if you'd prefer that the name and/or return values be consistent across both repos, I can change it.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 5 files at r2, 8 of 8 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

___
*[`machine/corpora/paratext_project_settings.py` line 23 at r4](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4XujN10nte1IwrTQyP:-O4g-3Op9Tr-04fzd6ZB:bmm5434) ([raw file](https://github.com/sillsdev/machine.py/blob/3c670cc90cd934ebc2c1639cab34cccf63bae6c7/machine/corpora/paratext_project_settings.py#L23)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

This is called `IsBookFileName` in Machine, and it returns a bool as well as an output parameter of `string bookId`. I could have had the machine.py version return a tuple with a bool and a str, but returning the bool seemed unnecessary since whenever the bool is false, the `bookId` is null, so we can just check that `book_id` isn't falsy in python. And since it no longer returns a bool, I renamed the method to `get_book_id` to align with what it's doing. However, if you'd prefer that the name and/or return values be consistent across both repos, I can change it.
</blockquote></details>

I don't have a problem with the change. When porting, I do allow for differences based on what is idiomatic for each language. I think it would be good to add a comment to clarify that the method returns `None` when the file name doesn't match the pattern of a book file name for the project.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115)* status: 9 of 27 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`machine/corpora/paratext_project_settings.py` line 23 at r4](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4XujN10nte1IwrTQyP:-O4gi01x-J4dd3axQAOG:b-gk1pbx) ([raw file](https://github.com/sillsdev/machine.py/blob/3c670cc90cd934ebc2c1639cab34cccf63bae6c7/machine/corpora/paratext_project_settings.py#L23)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't have a problem with the change. When porting, I do allow for differences based on what is idiomatic for each language. I think it would be good to add a comment to clarify that the method returns `None` when the file name doesn't match the pattern of a book file name for the project.
</blockquote></details>

Added the comment.
___
*[`machine/corpora/usfm_text_base.py` line 54 at r5](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4hDlw-D_vE6nm1ljDW:-O4hDlw-D_vE6nm1ljDX:bb6ctue) ([raw file](https://github.com/sillsdev/machine.py/blob/34d01588ab9e0de2c9748732b18e4f2d73d58638/machine/corpora/usfm_text_base.py#L54)):*
> ```Python
>                 f". Verse: {parser.state.verse_ref}, offset: {parser.state.verse_offset}, error: '{e}'"
>             )
>             raise RuntimeError(error_message) from e
> ```

This was type InvalidOperationException in Machine, and since I don't think there's an equivalent error type in python, I chose RuntimeError as close enough.

**Comment by mshannon-sil** [comment]
After this is merged in, I think I should be able to do everything that's remaining in one more PR, and then machine.py will be caught up to Machine for USFM generation.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 10 of 18 files at r5, 11 of 12 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil)

___
*[`machine/corpora/scripture_ref.py` line 107 at r7](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4ld0UwAQUGkt-GJrZX:-O4ld0Ux4r180WIfxtp2:b-e8almo) ([raw file](https://github.com/sillsdev/machine.py/blob/463dc5c76d158e14f87338427d1633308b3bfe3d/machine/corpora/scripture_ref.py#L107)):*
> ```Python
>                 return res
> 
>         return (len(self.path) > len(other.path)) - (len(self.path) < len(other.path))
> ```

This definitely works, but it is difficult for me to understand. It would be more verbose, but it would be clearer if you used `if ... elif ... else` to return the correct value.
___
*[`machine/scripture/verse_ref.py` line 410 at r7](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4leFk50f76Uw0Ti9Wv:-O4leFk66H0ePUCVwUbn:b25xwdd) ([raw file](https://github.com/sillsdev/machine.py/blob/463dc5c76d158e14f87338427d1633308b3bfe3d/machine/scripture/verse_ref.py#L410)):*
> ```Python
>             if result != 0:
>                 return result
>         return (len(verse_list) > len(other_verse_list)) - (len(verse_list) < len(other_verse_list))
> ```

See my other comment.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115)* status: 28 of 30 files reviewed, 2 unresolved discussions (waiting on @ddaspit)

___
*[`machine/corpora/scripture_ref.py` line 107 at r7](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4ld0UwAQUGkt-GJrZX:-O4pJpbj-a86sp61InOP:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/463dc5c76d158e14f87338427d1633308b3bfe3d/machine/corpora/scripture_ref.py#L107)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This definitely works, but it is difficult for me to understand. It would be more verbose, but it would be clearer if you used `if ... elif ... else` to return the correct value.
</blockquote></details>

Done.
___
*[`machine/scripture/verse_ref.py` line 410 at r7](https://reviewable.io/reviews/sillsdev/machine.py/115#-O4leFk50f76Uw0Ti9Wv:-O4pJoymE_jyLfcFQVnn:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/463dc5c76d158e14f87338427d1633308b3bfe3d/machine/scripture/verse_ref.py#L410)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my other comment.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/115#-:-O4qPUgv9KQGZS4z3A4U:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
