### PR TITLE
Set HuggingFaceNmtEngine to not truncate by default

### PR DESCRIPTION
**Pull request by ddaspit**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/45)

### CODE REVIEW

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/45)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/45#-NhDEaSmELyFpYl_icBK:-NhDEaSmELyFpYl_icBL:b-sydke6) ([raw file](https://github.com/sillsdev/machine.py/blob/167f3e93fcdd84044c95e231a88282acf47cf025/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L74)):*
> ```Python
>             num_beams=self._config.huggingface.generate_params.num_beams,
>             batch_size=self._config.huggingface.generate_params.batch_size,
>             truncation=TruncationStrategy.LONGEST_FIRST,
> ```

Wouldn't this cause memory issues with the odd super-long segment of 2000 tokens?  Why the need for the change?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/45)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/45#-NhDEaSmELyFpYl_icBK:-NhDHnKh5wBo4yMehtDm:b5zql4x) ([raw file](https://github.com/sillsdev/machine.py/blob/167f3e93fcdd84044c95e231a88282acf47cf025/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L74)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Wouldn't this cause memory issues with the odd super-long segment of 2000 tokens?  Why the need for the change?
</blockquote></details>

This doesn't change the behavior for Serval at all. It simply changes the default truncation strategy for the `HuggingFaceNmtEngine` back to not truncate. Serval jobs still use the longest first truncation strategy. We are just now setting it in the `HuggingFaceNmtModelFactory`, which is the more appropriate place.

**Comment by johnml1135** [comment]
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/45#-NhDEaSmELyFpYl_icBK:-NhDOgio3rdI8R2gbr58:b2ni9bh) ([raw file](https://github.com/sillsdev/machine.py/blob/167f3e93fcdd84044c95e231a88282acf47cf025/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L74)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This doesn't change the behavior for Serval at all. It simply changes the default truncation strategy for the `HuggingFaceNmtEngine` back to not truncate. Serval jobs still use the longest first truncation strategy. We are just now setting it in the `HuggingFaceNmtModelFactory`, which is the more appropriate place.
</blockquote></details>

ok.

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/45)* status: 0 of 10 files reviewed, all discussions resolved

**Pull request merged**
