### PR TITLE
Add MT tutorial

### PR DESCRIPTION
**Pull request by ddaspit**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/129)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 80 at r1](https://reviewable.io/reviews/sillsdev/machine.py/129#-O9QQ3bjBGrmTlToIP6o:-O9QQ3bjBGrmTlToIP6p:bw966wg) ([raw file](https://github.com/sillsdev/machine.py/blob/1d507e1b88ffb4a2c033346f31d50f4eaa3609a1/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L80)):*
> ```Python
>             corpus,
>             src_lang=self._config.src_lang,
>             tgt_lang=self._config.trg_lang,
> ```

why are some trg and some tgt?  I thought we were only doing trg...

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/129)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/129)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 80 at r1](https://reviewable.io/reviews/sillsdev/machine.py/129#-O9QQ3bjBGrmTlToIP6o:-O9R16LO6MvaF1FtVMPy:b-x1ujx) ([raw file](https://github.com/sillsdev/machine.py/blob/1d507e1b88ffb4a2c033346f31d50f4eaa3609a1/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L80)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

why are some trg and some tgt?  I thought we were only doing trg...
</blockquote></details>

I was trying to make all of the parameter names consistent for the Huggingface classes, but I didn't want to break the integration with Serval, so I left `trg_lang` alone. I shouldn't have changed `add_unk_trg_tokens` in the `settings.yaml`, since that is potentially a breaking change with Serval and also makes it inconsistent with the `trg_lang` setting, so I changed it back. Unfortunately, that means that the jobs settings and the Huggingface classes are now inconsistent, but I willing to live with that, so we don't break Serval.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/129)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/129)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
