### PR TITLE
Config passing serval #45

### PR DESCRIPTION
**Pull request by mshannon-sil**
These updates are for creating the `build_options` argument, moving `max_steps` inside `build_options`, and only doing inference when the user does not provide training data.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`dockerfile` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfkaims7mlOq1fiOM5r:-Nfkaims7mlOq1fiOM5s:b7r1vf5) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/dockerfile#L2)):*
> ```
> #compatability with Tensorflow 2.6.0 as per https://www.tensorflow.org/install/source#gpu
> ARG PYTHON_VERSION=3.8
> ```

This should be updated to 3.11 - to match what poetry is expecting.

**Comment by johnml1135** [comment]
*[`.devcontainer/dockerfile` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfkb6593sf2AObMmQk5:-Nfkb6593sf2AObMmQk6:b7m6g0c) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/.devcontainer/dockerfile#L2)):*
> ```
> #compatability with Tensorflow 2.6.0 as per https://www.tensorflow.org/install/source#gpu
> ARG PYTHON_VERSION=3.8
> ```

Update to python 3.11

**Comment by johnml1135** [comment]
*[`machine/jobs/build_nmt_engine.py` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkbUIdE52aNgbMDvD1:-NfkbUIdE52aNgbMDvD2:b-m1h3xc) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/build_nmt_engine.py#L41)):*
> ```Python
>         SETTINGS.update(args)
>         if args["build_options"]:
>             SETTINGS.build_options = json.loads(args["build_options"])
> ```

There should be a try-except here with an intelligent error about how the build_options were not parsable.

**Comment by johnml1135** [comment]
*[`machine/jobs/build_nmt_engine.py` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkbvWU2d_bsjBhld4M:-NfkbvWU2d_bsjBhld4N:bdjcg2e) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/build_nmt_engine.py#L74)):*
> ```Python
>     parser.add_argument("--trg-lang", required=True, type=str, help="Target language tag")
>     parser.add_argument("--clearml", default=False, action="store_true", help="Initializes a ClearML task")
>     parser.add_argument("--build-options", default={}, help="Build configurations")
> ```

Will this default really work?  What would happen if you parse it?  Shouldn't it be "{}"?

**Comment by johnml1135** [comment]
*[`machine/jobs/build_nmt_engine.py` line 40 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfkc3bV4pki__NKZQvx:-Nfkc3bV4pki__NKZQvy:b-lveclp) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/build_nmt_engine.py#L40)):*
> ```Python
> 
>         SETTINGS.update(args)
>         if args["build_options"]:
> ```

if args["build_options"] == "":
  args["build_options"] = "{}"

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcfLD5p6ru3B3AdH4:-NfkcfLD5p6ru3B3AdH5:b29dq9c) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L29)):*
> ```Python
>             source_corpus = self._shared_file_service.create_source_corpus()
>             target_corpus = self._shared_file_service.create_target_corpus()
>             parallel_corpus = source_corpus.align_rows(target_corpus)
> ```

We probably need a minimum size of target and source files.  We should check for it and throw if it does not exist.  @ddaspit - is it 500 lines?

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcfLD5p6ru3B3AdH4:-NfkcrHU3JSf3a0iGOhU:b7pqasf) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L29)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

We probably need a minimum size of target and source files.  We should check for it and throw if it does not exist.  @ddaspit - is it 500 lines?
</blockquote></details>

That is, a minimum number of aligned parallel_corpus.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 7 unresolved discussions (waiting on @ddaspit and @mshannon-sil)

___
*[`machine/jobs/nmt_engine_build_job.py` line 25 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcR1S6bwjmLQ_BhB2:-NfkcR1S6bwjmLQ_BhB3:b-btdju6) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L25)):*
> ```Python
>         self._nmt_model_factory.init()
> 
>         if self._shared_file_service.exists_source_corpus() and self._shared_file_service.exists_target_corpus():
> ```

Should we be also checking for a non-zero size?  I am unsure of the logic of Machine - will it create a target file if none exist?

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/jobs/build_nmt_engine.py` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkbvWU2d_bsjBhld4M:-NflNE3h2osDVcxklRHy:bs1ycb) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/build_nmt_engine.py#L74)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Will this default really work?  What would happen if you parse it?  Shouldn't it be "{}"?
</blockquote></details>

That default sets it to an empty dictionary. If build_options is an empty dictionary, then the check `if args["build_options"]:` evaluates to False and it's not parsed, leaving settings with the default values. However, I can change it to work with a default of "{}" if there's a benefit in doing it that way.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 8 unresolved discussions (waiting on @johnml1135 and @mshannon-sil)

___
*[`dockerfile` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfkaims7mlOq1fiOM5r:-Nfm09gJ8dIzqtXpQ_aO:bkagcl3) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/dockerfile#L2)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This should be updated to 3.11 - to match what poetry is expecting.
</blockquote></details>

Python 3.8 is fine. Machine.py supports 3.8-3.11.
___
*[`pyproject.toml` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfm-wpB9VAWdhU-Eu6L:-Nfm-wpB9VAWdhU-Eu6M:b-l3b1z6) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/pyproject.toml#L60)):*
> ```TOML
> networkx = "^2.6.3"
> charset-normalizer = "^2.1.1"
> setuptools = "^68.2.2"
> ```

What is setuptools needed for?
___
*[`machine/jobs/build_nmt_engine.py` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkbvWU2d_bsjBhld4M:-Nfm0rnR9YuiBHNACx-1:bkp4li2) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/build_nmt_engine.py#L74)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

That default sets it to an empty dictionary. If build_options is an empty dictionary, then the check `if args["build_options"]:` evaluates to False and it's not parsed, leaving settings with the default values. However, I can change it to work with a default of "{}" if there's a benefit in doing it that way.
</blockquote></details>

I would make the default an empty string or "{}". That way it is always the same type.
___
*[`machine/jobs/nmt_engine_build_job.py` line 25 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcR1S6bwjmLQ_BhB2:-Nfm2qCsCb0NgdXNiaGR:bi6e9ky) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L25)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should we be also checking for a non-zero size?  I am unsure of the logic of Machine - will it create a target file if none exist?
</blockquote></details>

Yes, that is correct. The source and target files will always exist. You need to check if the parallel corpus is empty. You can call `parallel_corpus.count(include_empty=False)` to get the training corpus size.
___
*[`machine/jobs/nmt_engine_build_job.py` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcfLD5p6ru3B3AdH4:-Nfm1qAG8YQYdROCHiPk:bdiz2pz) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L29)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

That is, a minimum number of aligned parallel_corpus.
</blockquote></details>

I wouldn't impose a minimum. We should leave it up to the calling application to decide.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 8 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`pyproject.toml` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfm-wpB9VAWdhU-Eu6L:-Nfm6LaqE0U773nkHtQd:bdyxjbh) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/pyproject.toml#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is setuptools needed for?
</blockquote></details>

I upgraded poetry and added setuptools so that it would pass the github actions test. It seemed kind of strange to me that it needed setuptools in poetry, so I tried removing it, but then it started failing again, so I kept it in. You can see all this in my commit history for the branch if you want to take a look.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 8 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 25 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcR1S6bwjmLQ_BhB2:-NfmH5um8J3lANGKW0ch:bv3vial) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, that is correct. The source and target files will always exist. You need to check if the parallel corpus is empty. You can call `parallel_corpus.count(include_empty=False)` to get the training corpus size.
</blockquote></details>

To be clear, if the user does not include training files and Machine generates them, does Machine always generate empty files for both the source and the target training files?

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 7 unresolved discussions (waiting on @johnml1135 and @mshannon-sil)

___
*[`pyproject.toml` line 60 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfm-wpB9VAWdhU-Eu6L:-NfmbzCz84lTkhFSD7Zg:bqluu3o) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/pyproject.toml#L60)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

I upgraded poetry and added setuptools so that it would pass the github actions test. It seemed kind of strange to me that it needed setuptools in poetry, so I tried removing it, but then it started failing again, so I kept it in. You can see all this in my commit history for the branch if you want to take a look.
</blockquote></details>

I removed setuptools from the pyproject.toml file. Machine.py already had a dependency on setuptools, it just needed to be updated to the latest version in the lock file.
___
*[`machine/jobs/nmt_engine_build_job.py` line 25 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfkcR1S6bwjmLQ_BhB2:-NfmaD2TDa76P_rc3mlf:br0oljm) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/machine/jobs/nmt_engine_build_job.py#L25)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

To be clear, if the user does not include training files and Machine generates them, does Machine always generate empty files for both the source and the target training files?
</blockquote></details>

In that case, Machine will generate empty source and target files. It is still possible for a calling application to provide source and target corpus files that are non-empty and the parallel corpus to be empty. This can occur if the source and target files do not have any aligned segments. That is why you should use `parallel_corpus.count(include_empty=False)` to determine if the parallel corpus is empty.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 6 unresolved discussions (waiting on @mshannon-sil)

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 30 at r3](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfqOqZm08deCIDGNjYe:-NfqOqZm08deCIDGNjYf:b-3tmw3a) ([raw file](https://github.com/sillsdev/machine.py/blob/b0fc2f90fb605173d27e0ca4dc9dd21ff24cf8c4/machine/jobs/nmt_engine_build_job.py#L30)):*
> ```Python
>         parallel_corpus = source_corpus.align_rows(target_corpus)
> 
>         if parallel_corpus.count(include_empty=False):
> ```

One more thing - there should probably be something put in the log for the else case like "no matching entries in the source and target corpus - skipping training".

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @mshannon-sil)

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 30 at r3](https://reviewable.io/reviews/sillsdev/machine.py/32#-NfqOqZm08deCIDGNjYe:-NfqbciF1py2oNwI9vo8:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/b0fc2f90fb605173d27e0ca4dc9dd21ff24cf8c4/machine/jobs/nmt_engine_build_job.py#L30)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

One more thing - there should probably be something put in the log for the else case like "no matching entries in the source and target corpus - skipping training".
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`dockerfile` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfkaims7mlOq1fiOM5r:-NfqiWWMBSRfRN4DyPl2:b-ws0ubt) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/dockerfile#L2)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Okay, I've left it at 3.8 for now, but I can upgrade it to 3.11 if we'd like.
</blockquote></details>

It's fine at 3.8 for now.  The TOML file allows it.

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32#-:-NfqifbGD8Ysy2gBJ8bY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`dockerfile` line 2 at r1](https://reviewable.io/reviews/sillsdev/machine.py/32#-Nfkaims7mlOq1fiOM5r:-Nfqti7UBx9Z8PSGB-F1:b-tfkt3t) ([raw file](https://github.com/sillsdev/machine.py/blob/24f101629f10de3a0db7bbfda223bc7d0b36ae95/dockerfile#L2)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It's fine at 3.8 for now.  The TOML file allows it.
</blockquote></details>

Talking with John, it would be helpful to upgrade python to the latest version since Python 3.11 is much faster than Python 3.8. However, the way the devcontainer dockerfile is set up right now, any python above 3.9 doesn't work with it, and after wrangling with it for over an hour today I think it would be more efficient to work on upgrading it after I get done what I need to for MVP.

**Review by ddaspit — APPROVED** [review]
We don't really need the `exists_source_corpus` and `exists_target_corpus` methods anymore, but I don't have a problem with leaving them in if you want.

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32#-:-NfvGRm770-OfGtsf-H_:boswi22)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
