### PR TITLE
Update learning rate for #116 and other small error

### PR DESCRIPTION
**Pull request by johnml1135**
#116

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/117)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
I don't think we are ready to make this change yet. We need to come up with a plan for how we are going to roll this out first.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/117#-:-O5Z3gkq35YTqomPdega:b-h5wpjn)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/117#-O5Z3dg6BpC46jyP1HGW:-O5Z3dg6BpC46jyP1HGX:b-djy3u6) ([raw file](https://github.com/sillsdev/machine.py/blob/af0194c3803c93c06d84c2a70df6011c3e09a927/machine/jobs/nmt_engine_build_job.py#L77)):*
> ```Python
>             model_trainer.train(progress=phase_progress, check_canceled=check_canceled)
>             model_trainer.save()
>             train_corpus_size = parallel_corpus.count()
> ```

Why was this change necessary?

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/117#-O5Z3dg6BpC46jyP1HGW:-O5Z7_2x4Y4fAj4NpsaJ:b4dlbvb) ([raw file](https://github.com/sillsdev/machine.py/blob/af0194c3803c93c06d84c2a70df6011c3e09a927/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this change necessary?
</blockquote></details>

I made a change for the word alignment - and made it incorrectly.  This is to fix the code.  I can make a separate PR for this if we are not ready for the learning rate changes.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/117)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/117#-O5Z3dg6BpC46jyP1HGW:-O5ZyMQb50UstZznuDZ6:bc78ah5) ([raw file](https://github.com/sillsdev/machine.py/blob/af0194c3803c93c06d84c2a70df6011c3e09a927/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I made a change for the word alignment - and made it incorrectly.  This is to fix the code.  I can make a separate PR for this if we are not ready for the learning rate changes.
</blockquote></details>

Yes, go ahead and make a separate PR for now.

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/117#-O5Z3dg6BpC46jyP1HGW:-O5yG7iNECrl1R0hIBy1:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/af0194c3803c93c06d84c2a70df6011c3e09a927/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, go ahead and make a separate PR for now.
</blockquote></details>

Done.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/117)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/117#-O5Z3dg6BpC46jyP1HGW:-OCe1lCl6MardnweZCiC:b5zxpeh) ([raw file](https://github.com/sillsdev/machine.py/blob/af0194c3803c93c06d84c2a70df6011c3e09a927/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If the `model_trainer.stats.train_corpus_size` is not returning the correct value, it should be fixed in the trainer class.

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/117#-O5Z3dg6BpC46jyP1HGW:-OCe2wo90ayLL7HdqBo4:b-goimb5) ([raw file](https://github.com/sillsdev/machine.py/blob/af0194c3803c93c06d84c2a70df6011c3e09a927/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If the `model_trainer.stats.train_corpus_size` is not returning the correct value, it should be fixed in the trainer class.
</blockquote></details>

I believe the issue may have been resolved elsewhere.  Let's move it out of this PR.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/117#-:-OCe3ln3ExzVK3PrXOGO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
