### PR TITLE
fix docker build

### PR DESCRIPTION
**Pull request by johnml1135**
#135 - fix docker build

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/136)

### CODE REVIEW

**Comment by johnml1135** [comment]
Existing error:
```
310.3 Building wheels for collected packages: sacremoses
310.3   Building wheel for sacremoses (setup.py): started
310.6   Building wheel for sacremoses (setup.py): finished with status 'done'
310.6   Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895239 sha256=6ebf61b8a2d67522865e62e21780330febea4dfb15a19f117f907f7480ba9e39
310.6   Stored in directory: /tmp/pip-ephem-wheel-cache-yv62bzgp/wheels/23/9c/68/179ccbdb91b8111e62b7518d3cf19e1f6af16440f1c146f93e
310.6 Successfully built sacremoses
311.2 Installing collected packages: sortedcontainers, sentencepiece, pytz, mpmath, xxhash, urllib3, tzdata, typing-extensions, tqdm, sympy, sil-thot, safetensors, rpds-py, regex, pyyaml, python-dateutil, pyparsing, pyjwt, pyarrow, psutil, propcache, pillow, pathlib2, packaging, orderedmultidict, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, multidict, markupsafe, json-stream, joblib, jmespath, idna, fsspec, frozenlist, filelock, dynaconf, dill, click, charset-normalizer, certifi, attrs, aiohappyeyeballs, yarl, triton, sacremoses, requests, referencing, pandas, nvidia-cusparse-cu12, nvidia-cudnn-cu12, multiprocess, jinja2, furl, botocore, aiosignal, s3transfer, nvidia-cusolver-cu12, jsonschema-specifications, huggingface-hub, aiohttp, torch, tokenizers, jsonschema, boto3, transformers, datasets, clearml, accelerate
315.5   Attempting uninstall: pyparsing
315.5     Found existing installation: pyparsing 3.1.1
315.5 ERROR: Cannot uninstall pyparsing 3.1.1, RECORD file not found. Hint: The package was installed by debian.
------
```

**Review by mshannon-sil — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/136)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135 and @TaperChipmunk32)

___
*[`pyproject.toml` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine.py/136#-OAQPvggC8H73AfanzaU:-OAQPvgh5kDOuc5KhTCR:bgu7hsk) ([raw file](https://github.com/sillsdev/machine.py/blob/1fe99865b485199c8a57a883b5cb9783633a7bf1/pyproject.toml#L62)):*
> ```TOML
> networkx = "^3"
> charset-normalizer = "^2.1.1"
> urllib3 = "<2"
> ```

Unless I'm missing something, it looks like urllib3 was added to the pyproject.toml, but removed from the poetry.lock file.

**Comment by johnml1135** [comment]
*[`pyproject.toml` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine.py/136#-OAQPvggC8H73AfanzaU:-OAT0fMM1gzcaIs_Q38w:bvnoh3c) ([raw file](https://github.com/sillsdev/machine.py/blob/1fe99865b485199c8a57a883b5cb9783633a7bf1/pyproject.toml#L62)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Unless I'm missing something, it looks like urllib3 was added to the pyproject.toml, but removed from the poetry.lock file.
</blockquote></details>

That's how it was resolved.  I don't know about the urllib3 issue - I just added it from the direction of @TaperChipmunk32.

**Comment by johnml1135** [comment]
The docker images are creating now.  They are all running much faster too!

**Comment by TaperChipmunk32** [comment]
> _[`pyproject.toml` line 62 at r1](https://reviewable.io/reviews/sillsdev/machine.py/136#-OAQPvggC8H73AfanzaU:-OAT0fMM1gzcaIs_Q38w:bvnoh3c) ([raw file](https://github.com/sillsdev/machine.py/blob/1fe99865b485199c8a57a883b5cb9783633a7bf1/pyproject.toml#L62)):_
> Previously, mshannon-sil wrote…
> 
> That's how it was resolved. I don't know about the urllib3 issue - I just added it from the direction of @TaperChipmunk32.

This was the error from the build in actions: "The `urllib3` package has the following compatible candidates `[Package('urllib3', '1.26.20')]`;  but, the exporter dependency walker previously elected `urllib3 (2.2.3)` which is not compatible with the dependency `urllib3 (>=1.25.4,<1.27)`. Please contribute to `poetry-plugin-export` to solve this problem."

**Review by TaperChipmunk32 — APPROVED** [review]

**Review by mshannon-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/136)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`dockerfile` line 66 at r3](https://reviewable.io/reviews/sillsdev/machine.py/136#-OAT9pWOD2LIZopdoOoC:-OAT9pWOD2LIZopdoOoD:bjw9cdh) ([raw file](https://github.com/sillsdev/machine.py/blob/7a16abc34bcce4ed373c56850e2b60277ba9151e/dockerfile#L66)):*
> ```
> RUN python -m pip install --no-deps . && rm -r /root/*
> ENV CLEARML_AGENT_SKIP_PYTHON_ENV_INSTALL=1 \
>     CLEARML_AGENT_SKIP_PIP_VENV_INSTALL=1
> ```

This environment variable `CLEARML_AGENT_SKIP_PIP_VENV_INSTALL` should be unnecessary, since you're already skipping the python env install with the other environment variable, and according to the documentation it's supposed to take a path to an existing python environment rather than a boolean value: https://clear.ml/docs/latest/docs/clearml_agent/clearml_agent_env_var/
___
*[`dockerfile.cpu_only` line 45 at r3](https://reviewable.io/reviews/sillsdev/machine.py/136#-OATAudbEJm66Et4DOTY:-OATAudbEJm66Et4DOTZ:b-jinl8k) ([raw file](https://github.com/sillsdev/machine.py/blob/7a16abc34bcce4ed373c56850e2b60277ba9151e/dockerfile.cpu_only#L45)):*
> ```
> RUN python -m pip install --no-deps . && rm -r /root/*
> ENV CLEARML_AGENT_SKIP_PYTHON_ENV_INSTALL=1 \
>     CLEARML_AGENT_SKIP_PIP_VENV_INSTALL=1
> ```

Same comment as in the regular dockerfile.

**Comment by johnml1135** [comment]
*[`dockerfile` line 66 at r3](https://reviewable.io/reviews/sillsdev/machine.py/136#-OAT9pWOD2LIZopdoOoC:-OATPDHh7hsGG5VZinnb:bb7f2mf) ([raw file](https://github.com/sillsdev/machine.py/blob/7a16abc34bcce4ed373c56850e2b60277ba9151e/dockerfile#L66)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

This environment variable `CLEARML_AGENT_SKIP_PIP_VENV_INSTALL` should be unnecessary, since you're already skipping the python env install with the other environment variable, and according to the documentation it's supposed to take a path to an existing python environment rather than a boolean value: https://clear.ml/docs/latest/docs/clearml_agent/clearml_agent_env_var/
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`dockerfile.cpu_only` line 45 at r3](https://reviewable.io/reviews/sillsdev/machine.py/136#-OATAudbEJm66Et4DOTY:-OATPjpy0FC-AM0F0pz3:bb7f2mf) ([raw file](https://github.com/sillsdev/machine.py/blob/7a16abc34bcce4ed373c56850e2b60277ba9151e/dockerfile.cpu_only#L45)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Same comment as in the regular dockerfile.
</blockquote></details>

done

**Review by mshannon-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/136#-:-OATR2Fl6cHumnE2nnVQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
