### PR TITLE
Fix USX corpus issues

### PR DESCRIPTION
**Pull request by ddaspit**
- Fix incorrect handling of descriptive titles
- Add support for tables

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/138)

### CODE REVIEW

**Comment by johnml1135** [comment]
Is this issue in Machine as well?

**Comment by johnml1135** [comment]
*[`tests/corpora/test_usx_memory_text.py` line 35 at r1](https://reviewable.io/reviews/sillsdev/machine.py/138#-OAz0Tmy-LS3yIgRsfTI:-OAz0Tmz1rcxek2s4n9F:bgieuyb) ([raw file](https://github.com/sillsdev/machine.py/blob/0bde8dbfa1030c0dd3d38466be5d27d79fb55908/tests/corpora/test_usx_memory_text.py#L35)):*
> ```Python
>     <row style="tr">
>       <cell style="tc1" align="start"><verse number="1" style="v" />Chapter</cell>
>       <cell style="tcr2" align="end">1</cell>
> ```

I am assuming that this is how tables are normally defined in USX.  Is there any range of how they are defined?  Are there edge cases that are not being caught?

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/138)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
Yes, Machine.NET probably has the same issues.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/138#-:-OB0rHgwEtBBx__jORmC:b-q50ktw)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/corpora/test_usx_memory_text.py` line 35 at r1](https://reviewable.io/reviews/sillsdev/machine.py/138#-OAz0Tmy-LS3yIgRsfTI:-OB0rLh68VhguGZU8Ipn:b-2cq96i) ([raw file](https://github.com/sillsdev/machine.py/blob/0bde8dbfa1030c0dd3d38466be5d27d79fb55908/tests/corpora/test_usx_memory_text.py#L35)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I am assuming that this is how tables are normally defined in USX.  Is there any range of how they are defined?  Are there edge cases that are not being caught?
</blockquote></details>

This is the only way that they are defined in USX. There could be edge cases, but I'm not aware of any.

**Comment by johnml1135** [comment]
New issue opened: https://github.com/sillsdev/machine/issues/268

**Pull request merged**
