### PR TITLE
small fix for NMT build job

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/119)

### CODE REVIEW

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/119)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/119#-O5tBM4839lfo8gAzEmV:-O5tBM4839lfo8gAzEmW:b-djy3u6) ([raw file](https://github.com/sillsdev/machine.py/blob/1b848ec3fdf143d9b2a48da3b7cb3ef88cdd55ab/machine/jobs/nmt_engine_build_job.py#L77)):*
> ```Python
>             model_trainer.train(progress=phase_progress, check_canceled=check_canceled)
>             model_trainer.save()
>             train_corpus_size = parallel_corpus.count()
> ```

Why was this change necessary?

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/119#-O5tBM4839lfo8gAzEmV:-O5wl8mO2mebu3TxjNIk:bm2w7n1) ([raw file](https://github.com/sillsdev/machine.py/blob/1b848ec3fdf143d9b2a48da3b7cb3ef88cdd55ab/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this change necessary?
</blockquote></details>

When I was refactoring for SMT engines split out, I was mirroring the return type, returning the train corpus size.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/119)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/119#-O5tBM4839lfo8gAzEmV:-O5ya-SSDmZV2wI-6_oL:bje6ikq) ([raw file](https://github.com/sillsdev/machine.py/blob/1b848ec3fdf143d9b2a48da3b7cb3ef88cdd55ab/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

When I was refactoring for SMT engines split out, I was mirroring the return type, returning the train corpus size.
</blockquote></details>

`parallel_corpus.count()` will result in the full parallel corpus being read, so it would be better to use `model_trainer.stats.train_corpus_size`. I looked at `HuggingFaceNmtModelTrainer` and it looks like it might not be properly setting `train_corpus_size`. We should fix that bug instead.

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 77 at r1](https://reviewable.io/reviews/sillsdev/machine.py/119#-O5tBM4839lfo8gAzEmV:-O61cKApDwGxxLXZpy3X:bj976cl) ([raw file](https://github.com/sillsdev/machine.py/blob/1b848ec3fdf143d9b2a48da3b7cb3ef88cdd55ab/machine/jobs/nmt_engine_build_job.py#L77)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`parallel_corpus.count()` will result in the full parallel corpus being read, so it would be better to use `model_trainer.stats.train_corpus_size`. I looked at `HuggingFaceNmtModelTrainer` and it looks like it might not be properly setting `train_corpus_size`. We should fix that bug instead.
</blockquote></details>

I looked at the code and can't tell where it should be fixed (added to).  If you already know what fix needs to be made, can you go ahead and make it?

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/119)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 370 at r2](https://reviewable.io/reviews/sillsdev/machine.py/119#-O634Hbn3x8DemlOGKB6:-O634Hbn3x8DemlOGKB7:b-ci342d) ([raw file](https://github.com/sillsdev/machine.py/blob/6df7ece3f552ac0206b363bebf44b338a24bea1b/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L370)):*
> ```Python
>         self._metrics = train_result.metrics
>         self._metrics["train_samples"] = len(train_dataset)
>         self._stats.train_corpus_size = len(train_dataset)
> ```

You should compute the length once. This might require iterating over the entire dataset.
___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 382 at r2](https://reviewable.io/reviews/sillsdev/machine.py/119#-O634dPn8-64TUWFUJfB:-O634dPo7bHizJ1ax2nU:b-f7py) ([raw file](https://github.com/sillsdev/machine.py/blob/6df7ece3f552ac0206b363bebf44b338a24bea1b/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L382)):*
> ```Python
>         self._trainer.save_state()
>         if isinstance(self._model, PreTrainedModel):
>             model: PreTrainedModel = self._model
> ```

This shouldn't be necessary. The type checker can infer the type from the `isinstance` call.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 370 at r2](https://reviewable.io/reviews/sillsdev/machine.py/119#-O634Hbn3x8DemlOGKB6:-O67Cor53iOhpX-McS0J:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/6df7ece3f552ac0206b363bebf44b338a24bea1b/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L370)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should compute the length once. This might require iterating over the entire dataset.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 382 at r2](https://reviewable.io/reviews/sillsdev/machine.py/119#-O634dPn8-64TUWFUJfB:-O67EkV_2SP7jn6KhnS_:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/6df7ece3f552ac0206b363bebf44b338a24bea1b/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L382)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This shouldn't be necessary. The type checker can infer the type from the `isinstance` call.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/119#-:-O67F1B_--O54zB-bIj0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
