### PR TITLE
OOM error fixing

### PR DESCRIPTION
**Pull request by johnml1135**
#52 
Fix out of memory errors by gradually backing off of engine batch size.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58)

### CODE REVIEW

**Comment by johnml1135** [comment]
Testing:
```

[WARNING|text2text_generation.py:311] 2023-11-09 15:34:53,499 >> Your input_length: 937 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-09 15:34:59
2023-11-09 15:34:57,105 - machine.jobs.nmt_engine_build_job - INFO - Out of memory error, reducing batch size to 8
[INFO|tokenization_utils_base.py:2041] 2023-11-09 15:34:57,107 >> loading file sentencepiece.bpe.model
[INFO|tokenization_utils_base.py:2041] 2023-11-09 15:34:57,107 >> loading file tokenizer.json
[INFO|tokenization_utils_base.py:2041] 2023-11-09 15:34:57,107 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2041] 2023-11-09 15:34:57,107 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2041] 2023-11-09 15:34:57,107 >> loading file tokenizer_config.json
[WARNING|logging.py:290] 2023-11-09 15:34:57,553 >> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[WARNING|text2text_generation.py:311] 2023-11-09 15:34:57,566 >> Your input_length: 529 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-09 15:35:05
[WARNING|text2text_generation.py:311] 2023-11-09 15:35:00,315 >> Your input_length: 937 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
2023-11-09 15:35:03,667 - machine.jobs.build_nmt_engine - INFO - Finished
2023-11-09 15:35:16
Process completed successfully
```

**Review by ddaspit — CHANGES_REQUESTED** [review]
I think this would be simpler if we added this as a feature of the `HuggingFaceNmtEngine` class. I think it is something that would be generally useful. We could pass in a parameter to the constructor of the class to turn it on. The parameter could be a number between 0 and 1 with a default value of 1. The value would be multiplied by the current batch size to get the new batch size. We could call it `oom_batch_size_backoff_factor` or something like that. No other code would need to be changed. If it is unclear what I am suggesting, I can implement it.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58#-:-Niq3z642cU3Iy03YuyF:b-nbzwzu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
If you would like to redo the implementation, go ahead.  What I have now works and you should be able to pull a lot from it.

**Review by johnml1135 — COMMENTED** [review]
Please let me take a last review of the changes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58#-:-NiqAMgVECbJtVBQ9uNr:b-1mabz5)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/settings.yaml` line 38 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji0NRc-NpzEFbURAwZ:-Nji0NRdA9l1-nu3_3Kz:b9lhnie) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/jobs/settings.yaml#L38)):*
> ```YAML
>     parent_model_name: facebook/nllb-200-distilled-600M
>     train_params:
>       group_by_length: false
> ```

We did you disable grouping by length?
___
*[`machine/translation/nmt_translation_engine.py` line 9 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Njhyu3E5HsVHyMURR3X:-Njhyu3E5HsVHyMURR3Y:b-mc77n2) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/nmt_translation_engine.py#L9)):*
> ```Python
> 
> 
> class NmtTranslationEngine(TranslationEngine, ContextManager["NmtTranslationEngine"]):
> ```

This interface isn't needed. You can remove it.
___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 68 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-NjhzjLY8EELkNa5NnwO:-NjhzjLY8EELkNa5NnwP:b-c5q7rc) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L68)):*
> ```Python
>         batch_size = self._pipeline_kwargs.pop("batch_size")
>         if batch_size is not None:
>             self._batch_size = int(batch_size)  # type: ignore[assignment]
> ```

What is causing the type error? You shouldn't need to ignore the error. Use `cast` if necessary.
___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 70 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-NjhzX3v8kVeP5jlYYwX:-NjhzX3v8kVeP5jlYYwY:b-a4ypsd) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L70)):*
> ```Python
>             self._batch_size = int(batch_size)  # type: ignore[assignment]
>         else:
>             self._batch_size = 16
> ```

The default batch size should be 1.
___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-Nji-jBn5xXqC4YISSc1:bbmzri1) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
> ```Python
>                     all_results.extend(self._try_translate_n_batch(n, segments[step : step + self._batch_size]))
>                 return all_results
>             except Exception as e:
> ```

This will catch any exception and treat it like an OOM error. We need to be more specific here.
___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 109 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji0Gl06rvdzoR23-1S:-Nji0Gl06rvdzoR23-1T:b-slpiim) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L109)):*
> ```Python
>                 return all_results
>             except Exception as e:
>                 if self._oom_batch_size_backoff_multiplier >= 0.9999:
> ```

We should also check if the current batch size is 1.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58)* status: all files reviewed, 9 unresolved discussions (waiting on @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 137 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji16Lk33XYCtHnLPOF:-Nji16Ll9BwL-nVYzOfD:b-r2mkvz) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L137)):*
> ```Python
>         set_seed(self._training_args.seed)
> 
>         logger.info("Initializing tokenizer.")
> ```

This should be moved to the line that actually initializes the tokenizer.
___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 197 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji1Cbk5RXtC2sCN42J:-Nji1Cbk5RXtC2sCN42K:b-m3uzqs) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L197)):*
> ```Python
>             return AutoTokenizer.from_pretrained(str(tokenizer_dir), use_fast=True)
> 
>         logger.info("Checking for missing tokens.")
> ```

Move this into the `if` check.
___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 238 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji1HEt-9CwE2XqVADF:-Nji1HEt-9CwE2XqVADG:b-m3uzqs) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L238)):*
> ```Python
>                 tokenizer.id_to_lang_token[lang_id] = lang_code
> 
>         logger.info("Add new language codes as tokens.")
> ```

Move this into the `if` check.

**Comment by johnml1135** [comment]
*[`machine/jobs/settings.yaml` line 38 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji0NRc-NpzEFbURAwZ:-NjmIDe2CrCQuZ-yYQEO:b-73pg2z) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/jobs/settings.yaml#L38)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We did you disable grouping by length?
</blockquote></details>

I'll undo it - I was trying to reduce the startup time, but it didn't help.

**Comment by johnml1135** [comment]
*[`machine/translation/nmt_translation_engine.py` line 9 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Njhyu3E5HsVHyMURR3X:-NjmJUv_8kA9oHyBxfxD:bjcodx4) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/nmt_translation_engine.py#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This interface isn't needed. You can remove it.
</blockquote></details>

Forgot to remove them all done.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 68 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-NjhzjLY8EELkNa5NnwO:-NjmMTXV6UeJb1JpoTxk:b-eapff3) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L68)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is causing the type error? You shouldn't need to ignore the error. Use `cast` if necessary.
</blockquote></details>

Resolved.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-NjmMgZ19nS6Bu26Cn2b:bwgcabq) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This will catch any exception and treat it like an OOM error. We need to be more specific here.
</blockquote></details>

This is a known issue: https://github.com/pytorch/pytorch/issues/109961.  It will be addressed here: https://github.com/sillsdev/machine.py/issues/67.  Made updates for now incase there is a different type of error.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 109 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji0Gl06rvdzoR23-1S:-NjmR55r0IQpAStilLLQ:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L109)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should also check if the current batch size is 1.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 137 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji16Lk33XYCtHnLPOF:-NjmRPp88ebgeQKJL9NI:bb6un1j) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L137)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be moved to the line that actually initializes the tokenizer.
</blockquote></details>

Done

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 197 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji1Cbk5RXtC2sCN42J:-NjmRcAU2aPAATOwvpf_:bb6un1j) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L197)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Move this into the `if` check.
</blockquote></details>

Done

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 238 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji1HEt-9CwE2XqVADF:-NjmRmQcEMG8ov05NHbF:bb6un1j) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L238)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Move this into the `if` check.
</blockquote></details>

Done

**Review by ddaspit — COMMENTED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-NjmnRxAEFV8Lj-FzPyx:bdshtq3) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is a known issue: https://github.com/pytorch/pytorch/issues/109961.  It will be addressed here: https://github.com/sillsdev/machine.py/issues/67.  Made updates for now incase there is a different type of error.
</blockquote></details>

I took a look at the issues in the Pytorch repo. There is a class (`torch.cuda.OutOfMemoryError`) that gets thrown for OOM errors that we can catch. It just doesn't inherit from `Exception`, so Pylance displays an error stating: `"OutOfMemoryError" is not a valid exception class`. We should be able to use `torch.cuda.OutOfMemoryError` and safely ignore the Pylance error.

Also, I don't think we should raise a new error. We should just rethrow the existing `OutOfMemoryError`.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-Njn02xF2I-nlYhpUWei:bf8m9xn) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I took a look at the issues in the Pytorch repo. There is a class (`torch.cuda.OutOfMemoryError`) that gets thrown for OOM errors that we can catch. It just doesn't inherit from `Exception`, so Pylance displays an error stating: `"OutOfMemoryError" is not a valid exception class`. We should be able to use `torch.cuda.OutOfMemoryError` and safely ignore the Pylance error.

Also, I don't think we should raise a new error. We should just rethrow the existing `OutOfMemoryError`.
</blockquote></details>

Ok.  Will fix and merge.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-NjnHENb0i4xEDcn3V90:b-vyimk5) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ok.  Will fix and merge.
</blockquote></details>

Actually, it won't work.  We can't rethrow a OutOfMemoryError because it is not actually an exception.  I think we will likely have to leave it as is.

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-NjnNBR88ukjkF6YewSU:b-e5u8fm) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Actually, it won't work.  We can't rethrow a OutOfMemoryError because it is not actually an exception.  I think we will likely have to leave it as is.
</blockquote></details>

I figured it out - fixing it.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-NjoCIgP7FqPiUquoHXK:b8f3hs6) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I figured it out - fixing it.
</blockquote></details>

This worked on my machine:
```
try:
    for step in range(0, outer_batch_size, self._batch_size):
        all_results.extend(self._try_translate_n_batch(n, segments[step : step + self._batch_size]))
    return all_results
except torch.cuda.OutOfMemoryError:  # type: ignore[reportGeneralTypeIssues]
    if self._oom_batch_size_backoff_multiplier >= 0.9999 or self._batch_size == 1:
        raise
    self._batch_size = max(int(round(self._batch_size * self._oom_batch_size_backoff_multiplier)), 1)
    logger.warn(f"Out of memory error caught, reducing batch size to {self._batch_size} and retrying.")
    self._pipeline = _TranslationPipeline(
        model=self._model,
        tokenizer=self._tokenizer,
        batch_size=self._batch_size,
        **self._pipeline_kwargs,
    )
```

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/58#-:-NjoNEoI1UEmTAvqqTV1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 108 at r2](https://reviewable.io/reviews/sillsdev/machine.py/58#-Nji-jBn5xXqC4YISSc0:-Njog0ZqBzp_67uRa2gC:b161cnr) ([raw file](https://github.com/sillsdev/machine.py/blob/9872305719a47c38eb2e1fb8d7ffae0f75681c4c/machine/translation/huggingface/hugging_face_nmt_engine.py#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This worked on my machine:
```
try:
    for step in range(0, outer_batch_size, self._batch_size):
        all_results.extend(self._try_translate_n_batch(n, segments[step : step + self._batch_size]))
    return all_results
except torch.cuda.OutOfMemoryError:  # type: ignore[reportGeneralTypeIssues]
    if self._oom_batch_size_backoff_multiplier >= 0.9999 or self._batch_size == 1:
        raise
    self._batch_size = max(int(round(self._batch_size * self._oom_batch_size_backoff_multiplier)), 1)
    logger.warn(f"Out of memory error caught, reducing batch size to {self._batch_size} and retrying.")
    self._pipeline = _TranslationPipeline(
        model=self._model,
        tokenizer=self._tokenizer,
        batch_size=self._batch_size,
        **self._pipeline_kwargs,
    )
```
</blockquote></details>

I checked it again - switching to ```
torch.cuda.OutOfMemoryError
``` - you are right.
```

**Pull request merged**
