### PR TITLE
Add TranslationSuggester and friends

### PR DESCRIPTION
**Pull request by ddaspit**
- replace Mockito with Decoy for mocking

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/49)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`machine/translation/edit_distance.py` line 57 at r1](https://reviewable.io/reviews/sillsdev/machine.py/49#-NhhDb3FASDVVslnb7uH:-NhhDb3FASDVVslnb7uI:b-uqaidk) ([raw file](https://github.com/sillsdev/machine.py/blob/8f6c7543f7d0b2e31c25893d3704a512f97416ff/machine/translation/edit_distance.py#L57)):*
> ```Python
>                 dist_matrix[i][j], _, _, _ = self._process_dist_matrix_cell(
>                     x, y, dist_matrix, use_prefix_del_op, j != y_count or is_last_item_complete, i, j
>                 )
> ```

Is there a way to speed this up more?  It looks very slow - list comprehension? cython?  I am assuming that this will be computed many times...

**Comment by johnml1135** [comment]
*[`machine/translation/edit_distance.py` line 63 at r1](https://reviewable.io/reviews/sillsdev/machine.py/49#-NhhE-3pCBoCdXscPpZT:-NhhE-3pCBoCdXscPpZU:b-v494zc) ([raw file](https://github.com/sillsdev/machine.py/blob/8f6c7543f7d0b2e31c25893d3704a512f97416ff/machine/translation/edit_distance.py#L63)):*
> ```Python
>     def _process_dist_matrix_cell(
>         self, x: Seq, y: Seq, dist_matrix: List[List[float]], use_prefix_del_op: bool, is_complete: bool, i: int, j: int
>     ) -> Tuple[float, int, int, EditOperation]:
> ```

Do we need to try to convert this to C or cython code?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/49)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`machine/translation/edit_distance.py` line 57 at r1](https://reviewable.io/reviews/sillsdev/machine.py/49#-NhhDb3FASDVVslnb7uH:-NhhW-IPEuJD2o362WTo:b-atrot6) ([raw file](https://github.com/sillsdev/machine.py/blob/8f6c7543f7d0b2e31c25893d3704a512f97416ff/machine/translation/edit_distance.py#L57)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is there a way to speed this up more?  It looks very slow - list comprehension? cython?  I am assuming that this will be computed many times...
</blockquote></details>

This is a dynamic programming algorithm. Generally, the best computational complexity that you can achieve for this algorithm is O(m*n). You can make small optimizations, but not anything significant.
___
*[`machine/translation/edit_distance.py` line 63 at r1](https://reviewable.io/reviews/sillsdev/machine.py/49#-NhhE-3pCBoCdXscPpZT:-NhhXLY_B3AbBfB1noI2:b-fzntpj) ([raw file](https://github.com/sillsdev/machine.py/blob/8f6c7543f7d0b2e31c25893d3704a512f97416ff/machine/translation/edit_distance.py#L63)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Do we need to try to convert this to C or cython code?
</blockquote></details>

This method is fairly simple. I don't think that converting it to C or Cython will give us much of a boost in performance.

**Comment by ddaspit** [comment]
I'm going to go ahead and merge this in, so I can start using it in silnlp. We can defer any optimizations until we have known performance issues.

**Pull request merged**
