### PR TITLE
Restrict build options to only update model hyperparameters

### LINKED ISSUE #86: Restrict build options to only update model hyperparameters
The way that the build options is currently implemented allows a user to override any config parameter, including `data_dir` and `model_type`. We should restrict what parameters can be overridden. The build options should be merged with the model settings, i.e. the `huggingface` settings object.

### PR DESCRIPTION
**Pull request by ddaspit**
- fixes #86

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/88)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`machine/jobs/settings.yaml` line 4 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_hzJ-3bCr0Go86Vpj:-Nl_hzJ-3bCr0Go86Vpk:b8bypx) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/settings.yaml#L4)):*
> ```YAML
>   model_type: huggingface
>   data_dir: ~/machine
>   pretranslation_batch_size: 1024
> ```

So, batch size is really pretranslation_batch_size, which is the size of corpus we try to pretranslate at the same time.  You don't want this to be editable by the user, hence not putting it in huggingface.

**Comment by johnml1135** [comment]
*[`machine/jobs/settings.yaml` line 18 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_iCH-0JCXlvOfqwcQ:-Nl_iCH-0JCXlvOfqwcR:b-fxcgtc) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/settings.yaml#L18)):*
> ```YAML
>       fp16: true
>       save_strategy: no
>       max_steps: 20000
> ```

max_steps goes under train_params, which is more appropriate.  I agree.

**Comment by johnml1135** [comment]
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 31 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_imwK64KdvThHtgtI:-Nl_imwK64KdvThHtgtJ:bv0xmw1) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L31)):*
> ```Python
>         # Use "max_steps" from root for backward compatibility
>         if "max_steps" in self._config.huggingface:
>             args["max_steps"] = self._config.huggingface.max_steps
> ```

So, let's see if I follow this logic.  a person can set max_steps from the root and it will work successfully, but the real place is to set it in `huggingface.tran_params.max_steps`.  The issue is that you took my updates at looking for max_steps in `self._config.huggingface` instead of just `self._config`.  Am I missing something?

**Comment by johnml1135** [comment]
*[`machine/jobs/build_nmt_engine.py` line 48 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_jdF72X8CtQlId_bU:-Nl_jdF72X8CtQlId_bV:bw0psvx) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/build_nmt_engine.py#L48)):*
> ```Python
> 
>         SETTINGS.update(args)
>         model_type = cast(str, SETTINGS.model_type).lower()
> ```

So, let's see if I get this.  In settings.yml, there is a model_type parameter, here Huggingface.  That is taken from settings.yml without being tampered by any input arguments.  Then, any `build_options` given to Serval end up going under the current `model_type`, as seen a few lines below.  This seems sensible enough, except that, why not rename `huggingface` to `build_options` in settings.yml?  The `model_type` is already specified and it will be more clear in the documentation why the `build_options` map to ... `build_options`.

**Comment by johnml1135** [comment]
*[`machine/jobs/huggingface/hugging_face_nmt_model_factory.py` line 31 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_imwK64KdvThHtgtI:-Nl_lqZBCwV1BBnWxvq_:b-hs4x17) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/huggingface/hugging_face_nmt_model_factory.py#L31)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, let's see if I follow this logic.  a person can set max_steps from the root and it will work successfully, but the real place is to set it in `huggingface.tran_params.max_steps`.  The issue is that you took my updates at looking for max_steps in `self._config.huggingface` instead of just `self._config`.  Am I missing something?
</blockquote></details>

I read over the import of the settings and I see what you are doing now.  My main concern is the above concern to rename the `huggingface` group just `build_options`.

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 89 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_mHlc8dYMTpkNBsMz:-Nl_mHlc8dYMTpkNBsN-:bec6xzr) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/nmt_engine_build_job.py#L89)):*
> ```Python
>             current_inference_step = 0
>             phase_progress(ProgressStatus.from_step(current_inference_step, inference_step_count))
>             batch_size = self._config["pretranslation_batch_size"]
> ```

If `pretranslation_batch_size` will not be changed in any meaningful way for any meaningful reason, why include it?  It isn't the batch size that the GPU uses for doing Pretranslations but the number of segments that are pulled from the source and handled at one time.  Why not just set a constant to 1024 and be done with it?

**Comment by johnml1135** [comment]
*[`tests/jobs/test_nmt_engine_build_job.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_mltDEukSBUB4UzbB:-Nl_mltE2tUA6F1_zC0l:b-gugoga) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/tests/jobs/test_nmt_engine_build_job.py#L37)):*
> ```Python
> class _TestEnvironment:
>     def __init__(self, decoy: Decoy) -> None:
>         config = {"src_lang": "es", "trg_lang": "en", "pretranslation_batch_size": 100}
> ```

Why would this need to be 100 here?  (see other comment on `pretranslation_batch_size`

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/88)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/88)* status: all files reviewed, 5 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/build_nmt_engine.py` line 48 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_jdF72X8CtQlId_bU:-NldR0ce03viuJrWd1_9:b-g7laqg) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/build_nmt_engine.py#L48)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, let's see if I get this.  In settings.yml, there is a model_type parameter, here Huggingface.  That is taken from settings.yml without being tampered by any input arguments.  Then, any `build_options` given to Serval end up going under the current `model_type`, as seen a few lines below.  This seems sensible enough, except that, why not rename `huggingface` to `build_options` in settings.yml?  The `model_type` is already specified and it will be more clear in the documentation why the `build_options` map to ... `build_options`.
</blockquote></details>

If we support multiple model types, we can include the parameters for the different model types in the same settings file.
___
*[`machine/jobs/nmt_engine_build_job.py` line 89 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_mHlc8dYMTpkNBsMz:-NldRRlTDP5pxJwmny0P:bkbmz0g) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/nmt_engine_build_job.py#L89)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If `pretranslation_batch_size` will not be changed in any meaningful way for any meaningful reason, why include it?  It isn't the batch size that the GPU uses for doing Pretranslations but the number of segments that are pulled from the source and handled at one time.  Why not just set a constant to 1024 and be done with it?
</blockquote></details>

It could be a constant. I just made it a setting, so it would be slightly easier to tweak if we need to.
___
*[`machine/jobs/settings.yaml` line 4 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_hzJ-3bCr0Go86Vpj:-NldRqyZ2DD3S1AdkyHB:b-ew7aaa) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/settings.yaml#L4)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, batch size is really pretranslation_batch_size, which is the size of corpus we try to pretranslate at the same time.  You don't want this to be editable by the user, hence not putting it in huggingface.
</blockquote></details>

That is correct. This is the number of source segments to buffer while generating translations. It is different than the training or inferencing batch size.
___
*[`tests/jobs/test_nmt_engine_build_job.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_mltDEukSBUB4UzbB:-NldrJay88P6Irj3xzp3:b-q7wv6z) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/tests/jobs/test_nmt_engine_build_job.py#L37)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why would this need to be 100 here?  (see other comment on `pretranslation_batch_size`
</blockquote></details>

It is mostly an arbitrary number for testing.

**Comment by johnml1135** [comment]
*[`machine/jobs/build_nmt_engine.py` line 48 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_jdF72X8CtQlId_bU:-Nle2ofuEINzoMW8CWE6:b-82mjdc) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/build_nmt_engine.py#L48)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If we support multiple model types, we can include the parameters for the different model types in the same settings file.
</blockquote></details>

I could go either way - ok.

**Comment by johnml1135** [comment]
*[`machine/jobs/nmt_engine_build_job.py` line 89 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_mHlc8dYMTpkNBsMz:-Nle3CpK0CMYxshIWLA-:b2ni9bh) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/machine/jobs/nmt_engine_build_job.py#L89)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It could be a constant. I just made it a setting, so it would be slightly easier to tweak if we need to.
</blockquote></details>

ok.

**Comment by johnml1135** [comment]
*[`tests/jobs/test_nmt_engine_build_job.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine.py/88#-Nl_mltDEukSBUB4UzbB:-Nle3Nkh7ydznAnePQgc:b2ni9bh) ([raw file](https://github.com/sillsdev/machine.py/blob/8b9234e858ee2abd6b9d0601ad8eb4b3be246237/tests/jobs/test_nmt_engine_build_job.py#L37)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is mostly an arbitrary number for testing.
</blockquote></details>

ok.

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/88)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit)

**Pull request merged**
